import * as previewEngineRuntime from './preview-engine/index.js';
import {
  ELK_FORCE_PREVIEW_ENGINE,
  ELK_LAYERED_PREVIEW_ENGINE,
  ELK_MRTREE_PREVIEW_ENGINE,
  ELK_RADIAL_PREVIEW_ENGINE,
  ELK_RECTPACKING_PREVIEW_ENGINE,
  ELK_STRESS_PREVIEW_ENGINE,
  FORCE_PREVIEW_PARAM_SPECS,
  FORCE_PREVIEW_ENGINE,
  PREVIEW_ENGINE_REGISTRY,
  SEQUENCE_PREVIEW_ENGINE,
  elkForcePreviewControlSpecs,
  elkLayeredPreviewControlSpecs,
  elkMrtreePreviewControlSpecs,
  elkRadialPreviewControlSpecs,
  elkRectpackingPreviewControlSpecs,
  elkStressPreviewControlSpecs,
  getPreviewEngine,
  listPreviewEngines,
  listPreviewEnginesBySidebarSection,
  registerPreviewEngine,
  resolvePreviewEngine,
  serializePreviewEngineManifest,
} from './preview-engine/index.js';
import {
  ELK_LAYERED_PARAM_SPECS,
  ELK_FORCE_PARAM_SPECS,
  ELK_MRTREE_PARAM_SPECS,
  ELK_RADIAL_PARAM_SPECS,
  ELK_RECTPACKING_PARAM_SPECS,
  ELK_STRESS_PARAM_SPECS,
  elkParamGroups,
} from '@diagram-generator/graph-layout-elk';
import {
  applyForceNodePatch,
  createInitialForceSnapshot,
  exportForceAuthoredSpec,
  exportForceSnapshot,
  tickForceSimulation,
  updateForceSimulationParams,
} from './force-runtime.js';

export const previewEngines = Object.freeze({
  registry: Object.freeze({
    PREVIEW_ENGINE_REGISTRY,
    getPreviewEngine,
    listPreviewEnginesBySidebarSection,
    listPreviewEngines,
    registerPreviewEngine,
    resolvePreviewEngine,
    serializePreviewEngineManifest,
    runtime: previewEngineRuntime,
  }),
  graph: Object.freeze({
    createPreviewEngineLayoutControlsRuntime: previewEngineRuntime.createPreviewEngineLayoutControlsRuntime,
    createPreviewEngineShellControllerRuntime: previewEngineRuntime.createPreviewEngineShellControllerRuntime,
  }),
  elk: Object.freeze({
    ELK_LAYERED_PREVIEW_ENGINE,
    ELK_FORCE_PREVIEW_ENGINE,
    ELK_STRESS_PREVIEW_ENGINE,
    ELK_MRTREE_PREVIEW_ENGINE,
    ELK_RADIAL_PREVIEW_ENGINE,
    ELK_RECTPACKING_PREVIEW_ENGINE,
    elkForcePreviewControlSpecs,
    elkLayeredPreviewControlSpecs,
    elkStressPreviewControlSpecs,
    elkMrtreePreviewControlSpecs,
    elkRadialPreviewControlSpecs,
    elkRectpackingPreviewControlSpecs,
    ELK_LAYERED_PARAM_SPECS,
    ELK_FORCE_PARAM_SPECS,
    ELK_STRESS_PARAM_SPECS,
    ELK_MRTREE_PARAM_SPECS,
    ELK_RADIAL_PARAM_SPECS,
    ELK_RECTPACKING_PARAM_SPECS,
    elkParamGroups,
    renderPreviewElkRawView: previewEngineRuntime.renderPreviewElkRawView,
  }),
  force: Object.freeze({
    FORCE_PREVIEW_ENGINE,
    FORCE_PREVIEW_PARAM_SPECS,
    createInitialForceSnapshot,
    updateForceSimulationParams,
    exportForceSnapshot,
    exportForceAuthoredSpec,
    tickForceSimulation,
    applyForceNodePatch,
  }),
  sequence: Object.freeze({
    SEQUENCE_PREVIEW_ENGINE,
  }),
});
