import * as previewShellRuntime from './preview-shell/index.js';
import * as previewEngineRuntime from './preview-engine/index.js';
import {
  ELK_LAYERED_PREVIEW_ENGINE,
  FORCE_PREVIEW_PARAM_SPECS,
  elkLayeredPreviewControlSpecs,
  FORCE_PREVIEW_ENGINE,
  SEQUENCE_PREVIEW_ENGINE,
  PREVIEW_ENGINE_REGISTRY,
  getPreviewEngine,
  listPreviewEnginesBySidebarSection,
  listPreviewEngines,
  registerPreviewEngine,
  renderPreviewElkDebugOverlay,
  renderPreviewElkRawView,
  resolvePreviewEngine,
  serializePreviewEngineManifest,
} from './preview-engine/index.js';
import {
  ELK_LAYERED_PARAM_SPECS,
  elkParamGroups,
} from '@diagram-generator/graph-layout-elk';
import {
  applyForceNodePatch,
  createInitialForceSnapshot,
  exportForceAuthoredSpec,
  exportForceSnapshot,
  tickForceSimulation,
  updateForceSimulationParams,
} from './force-runtime.js';
import { createLine } from './frame-model.js';
import {
  BODY_LINE_STEP,
  BODY_SIZE,
  GRID_GUTTER,
  ICON_SIZE,
  INSET,
  sizeToPx,
} from './tokens.js';
import { wrapTextLines } from './text-measure.js';
import { layoutFrameTree } from './layout.js';
import { resolveStyles } from './resolve-styles.js';
import { layoutElkFrameDiagram } from './elk-layout.js';
import { effectiveResolvedStrokeWidth } from './frame-classes.js';
import {
  annotationTextToSpec,
  frameOwnedTextBlocks,
  frameOwnedTextBlockRole,
  frameOwnedTextBlockGap,
} from './resolved-spec-typography.js';
import { layoutSequenceDiagram } from './sequence-layout/layout.js';
import { renderSequenceDiagramToSvg } from './sequence-layout/render-svg.js';
import { routeArrows } from './arrow-routing.js';
import { deserializeFrameWire, deserializeFrameDiagramWire } from './frame-serialize.js';

export {
  type Line,
  createLine,
  Fill,
  Border,
  Direction,
  Sizing,
  Align,
  Justify,
  type Arrow,
  createArrow,
  type LayoutState,
  type FrameInit,
  Frame,
  type PositionType,
  type FrameDiagramInit,
  FrameDiagram,
  type CoercedOverride,
  enforceFillHugInvariant,
} from './frame-model.js';

export {
  BASELINE_UNIT,
  DEFAULT_MAX_WIDTH_CHARS,
  NO_WRAP_MAX_WIDTH_CHARS,
  BLOCK_WIDTH,
  BOX_MIN_HEIGHT,
  INSET,
  DEFAULT_FRAME_STROKE_WIDTH,
  ICON_SIZE,
  BODY_LINE_STEP,
  BODY_SIZE,
  LINE_HEIGHTS_BY_SIZE,
  defaultLineStep,
  roundUpToGrid,
  sizeToPx,
  steppedLinesHeight,
  clampToConstraints,
  setActiveGridStep,
  getActiveGridStep,
} from './tokens.js';

export {
  type LineSpec,
  type TextMeasureRequest,
  type TextMeasureAdapter,
  estimateLineWidth,
  letterSpacingPx,
  letterSpacingAdvance,
  lineSpecToMeasureRequest,
  wrapTextLines,
  lineToSpec,
  linesToSpecs,
  MockTextAdapter,
} from './text-measure.js';

export {
  CanvasTextAdapter,
  type CanvasTextAdapterOptions,
} from './canvas-text-adapter.js';

export {
  distributeFillSpace,
  alignOffset,
  measure,
  remeasureWithWidthConstraints,
  place,
  layoutFrameTree,
  type LayoutOutput,
  type LayoutOptions,
} from './layout.js';

export {
  computeLevel,
  resolveStyles,
} from './resolve-styles.js';

export {
  frameHasTextContent,
  applyTextLayoutDefaults,
  hasCharWrapCap,
  maxWidthPxFromChars,
  resolveLeafTextWrapWidth,
} from './text-layout.js';

export {
  layoutElkFrameDiagram,
  type ElkLayoutOptions,
} from './elk-layout.js';

export {
  ELK_LAYERED_PARAM_SPECS,
  elkParamGroups,
  resolvedElkOptionsForFamily,
  layeredConfigForFamily,
} from '@diagram-generator/graph-layout-elk';

export { applyHeadingAsChild } from './heading-synthesis.js';

export {
  FRAME_CLASS_DEFS,
  applyFrameClass,
  strokeWidthForClass,
  effectiveResolvedStrokeWidth,
  type FrameClassDefinition,
  type FrameTextStyle,
} from './frame-classes.js';

export {
  annotationTextToSpec,
  frameOwnedHeadingToSpec,
  frameOwnedLabelToSpec,
  frameOwnedTextBlocks,
  frameOwnedTextBlockRole,
  frameOwnedTextBlockGap,
  resolvedSpecTypography,
  usesHeadingStyleSnapshot,
  type ResolvedSpecTypography,
} from './resolved-spec-typography.js';

export {
  applyForceNodePatch,
  createInitialForceSnapshot,
  exportForceAuthoredSpec,
  exportForceSnapshot,
  tickForceSimulation,
  updateForceSimulationParams,
  type ForceAuthoredSpec,
  type ForceLinkSpec,
  type ForceNodePatch,
  type ForceNodeSpec,
  type ForceRenderSpec,
  type ForceSimulationConfig,
  type ForceRuntimeLink,
  type ForceRuntimeNode,
  type ForceRuntimeSnapshot,
  type ForceSimulationSpec,
} from './force-runtime.js';

export {
  layoutSequenceDiagram,
  type SequenceLayoutConfig,
  type SequenceLayoutGroupSpan,
  type SequenceLayoutMessageRow,
  type SequenceLayoutNoteBox,
  type SequenceLayoutParticipantBox,
  type SequenceLayoutResult,
} from './sequence-layout/layout.js';

export { renderSequenceDiagramToSvg } from './sequence-layout/render-svg.js';
export type { SequenceSvgRenderOptions } from './sequence-layout/render-svg.js';

export {
  routeArrows,
} from './arrow-routing.js';
export type { RoutedArrow } from './arrow-routing.js';

export {
  normalizeSequenceDiagram,
  type NormalizeSequenceDiagramResult,
  type SequenceDiagramInput,
  type SequenceDiagramSpec,
  type SequenceGroup,
  type SequenceGroupInput,
  type SequenceLine,
  type SequenceMessage,
  type SequenceMessageInput,
  type SequenceModelDiagnostic,
  type SequenceNote,
  type SequenceNoteInput,
  type SequenceNotePlacement,
  type SequenceParticipant,
  type SequenceParticipantInput,
  type SequenceParticipantKind,
} from './sequence-layout/model.js';

export {
  applyPreviewSvgOverridesHost,
  applyPreviewSvgOverrides,
  applyPreviewSelectionStateSnapshot,
  clearPreviewSelectionState,
  captureEditorSnapshot,
  cloneEditorSnapshotValue,
  normalizeGridOverrides,
  parseEditorSnapshot,
  serializeEditorSnapshot,
  createLoadPreviewSvgHostOptions,
  createPreviewLoadFailureMarkup,
  createPreviewLoadLoadingMarkup,
  createPreviewLoadUnavailableMarkup,
  loadPreviewSvg,
  normalizePreviewLoadInvocation,
  resolvePreviewFrameTreeSeed,
  bindPreviewShellResize,
  EditorUndoStack,
  clampPreviewShellWidth,
  clearPreviewShellWidth,
  createOverridePatchCommand,
  createPreviewOverrideExportText,
  createPreviewMissingInspectorMarkup,
  createStatePatchCommand,
  overridePatchChanged,
  EditorStateStore,
  captureOverrideEntries,
  createEditorStateStore,
  PERSIST_FRAME_KEYS,
  UNSUPPORTED_PERSIST_FRAME_KEYS,
  PERSIST_INT_FRAME_KEYS,
  PERSIST_LOWER_FRAME_KEYS,
  RELAYOUT_FRAME_KEYS,
  UNDO_RELAYOUT_FRAME_KEYS,
  hasPreviewRelayoutFrameOverride,
  hasV3FrameOverride,
  filterRelayoutOverrideEntry,
  createSelectionActionInfo,
  createMultiSelectionInspectorViewModel,
  createMultiSelectionAlignState,
  createMultiSelectionContainerState,
  createMultiSelectionSizingState,
  resolveMultiSelectionInspectorState,
  createSingleSelectionAutolayoutState,
  createSingleSelectionInspectorViewModel,
  hasPreviewNodeTextContent,
  applySelectionStateMutation,
  applyReorderOrder,
  clampSelectionTarget,
  dispatchPreviewDragCompletion,
  dispatchPreviewDragMove,
  dispatchPreviewResizeMove,
  dispatchPreviewResizeCompletion,
  resolveDragCompletion,
  resolveResizeCompletion,
  collectRecursiveRelayoutEntries,
  createMultiSelectionResizeOverrides,
  createNudgeOverrideEntries,
  collectPreviewSelectionActionInfo,
  createSelectionTargetOverrideEntries,
  dispatchPreviewKeyboardShortcut,
  findPreviewArrowAtPoint,
  findDeepestPreviewComponent,
  findPreviewComponentAtDepth,
  flattenPreviewTreeEntries,
  formatPreviewOverrideSummary,
  initPreviewShellResizeBindings,
  initPreviewOverrideToolbar,
  bindPreviewStageSvgInteractionHost,
  bindPreviewStageSvgInteraction,
  clearPreviewSvgHoverState,
  clearPreviewCoercedOverrides,
  clearPreviewTransientLayoutOverrides,
  dispatchPreviewClearOverride,
  createPreviewRelayoutRuntimeState,
  createPreviewRelayoutRuntimeFromRuntime,
  createPreviewRelayoutRuntimeOptionsFromRuntime,
  createPreviewRelayoutRuntimeOptionsFromHost,
  clearPreviewReorderIndicator,
  collectPreviewCoercedKeys,
  collectPreviewMultiResizeSelection,
  createOriginalOverrideEntries,
  createPreviewDragStartState,
  createResizePersistencePlan,
  ensurePreviewSvgHitAreas,
  isAutolayoutParentLayout,
  colSpanToPx,
  createPreviewGridOverrides,
  createPreviewGridOverlayScene,
  createPreviewGridRuntimeFromEditorHost,
  createPreviewGridRuntimeHost,
  PREVIEW_STYLE_SEMANTICS,
  applyPreviewStyleFields,
  applyVisiblePreviewStyleOverride,
  applyMultiFramePropMutation,
  applyMultiFrameSizeMutation,
  applySingleFramePropMutation,
  applySingleFrameSizeMutation,
  autoFitPreviewArtboard,
  applyPreviewWaypointOverridesHost,
  bindPreviewGridControls,
  bindPreviewGridNumberInputSelection,
  cyclePreviewGuideModeHost,
  bindPreviewArrowSegmentInsertHandles,
  cancelPreviewTextEdit,
  createPreviewKeyboardRuntime,
  createPreviewKeyboardRuntimeFromHost,
  createPreviewWaypointDragState,
  cancelPreviewLiveResizeRelayout,
  createPreviewLiveResizeRuntimeFromHost,
  createPreviewLiveResizeRuntime,
  createPreviewPointerInteractionRuntimeFromHost,
  createPreviewPointerInteractionRuntime,
  createPreviewResizeInteractionRuntime,
  createPreviewResizeInteractionRuntimeFromHost,
  createPreviewTextEditRuntime,
  createPreviewTextEditRuntimeFromHost,
  collectPreviewArtboardBounds,
  collectPreviewSnapTargets,
  collectPreviewSubtreeRemovalIds,
  clampPreviewDragDeltaWithinParent,
  dispatchPreviewDragMoveHost,
  completePreviewResizeInteraction,
  completePreviewDragInteraction,
  completePreviewTextEdit,
  completePreviewWaypointDragInteraction,
  connectPreviewSse,
  createBootstrapPreviewEditorRuntimeOptionsFromHost,
  createBootstrapPreviewEditorHostOptionsFromRuntime,
  createLoadPreviewSvgHostOptionsFromRuntime,
  createPreviewBuildStatusUpdater,
  createPreviewEditorBootstrapFacadeFromEditorHost,
  createPreviewEditorBootstrapFacadeFromRuntime,
  createPreviewEditorSceneFacadeFromEditorHost,
  createPreviewEditorSceneFacadeFromRuntime,
  createPreviewEditorInteractionFacadeFromBrowserHost,
  createPreviewEditorInteractionFacadeFromEditorHost,
  createPreviewEditorInteractionFacadeFromRuntime,
  createPreviewGridEditorBrowserStateFromBrowserHost,
  createPreviewGridEditorInstallUnitFromEditorHost,
  createPreviewGridEditorInstallUnitFromBrowserHost,
  createPreviewGridEditorRuntimeFromBrowserHost,
  createPreviewEditorRuntimeSetFromEditorHost,
  createPreviewEditorRuntimeSetFromRuntime,
  createPreviewEditorRuntimeSetFromHost,
  createPreviewEditorRuntimeSet,
  createPreviewArrowWaypointRuntime,
  createPreviewSelectionChromeRuntimeFromHost,
  createPreviewSelectionChromeRuntime,
  createPreviewElkViewModeRuntimeFromBrowserHost,
  createPreviewElkViewModeRuntime,
  createPreviewInspectorDisplayRuntime,
  createPreviewInspectorMutationRuntime,
  createPreviewInspectorSelectionRuntime,
  bindPreviewEditorInspectorActionsFromBrowserHost,
  createPreviewEditorRelayoutFacadeFromEditorHost,
  createPreviewEditorRelayoutFacadeFromRuntime,
  createPreviewLiveResizeRelayoutState,
  createPreviewLayoutBridgeRuntimeFromBrowserHost,
  createPreviewStateRestoreRuntime,
  createPreviewStateRestoreRuntimeFromEditorHost,
  createPreviewRelayoutRuntimeFromEditorHost,
  createPreviewRelayoutRuntime,
  createPreviewOverrideToolbarHostOptions,
  createPreviewSaveClientRuntime,
  createPreviewSaveClientInitConfig,
  createPreviewStageBindingRuntimeFromHost,
  createPreviewStageBindingRuntime,
  createPreviewSelectionRuntime,
  collectPreviewFramesById,
  collectPreviewPlacedBounds,
  commitPreviewWaypointInsert,
  commitPreviewWaypointRemoval,
  deletePreviewSelectedFramesHost,
  dispatchPreviewDeleteFramesHost,
  dispatchPreviewDeleteFrames,
  dispatchPreviewGridControlChangeHost,
  dispatchPreviewGridControlChange,
  insertPreviewWaypoint,
  dispatchPreviewResizeMoveHost,
  dispatchPreviewRelayoutFailureHost,
  dispatchPreviewRelayoutSuccessHost,
  persistPreviewResizeToFrameOverrides,
  formatPreviewRelayoutStatusMessage,
  isPreviewFrameManagedTarget,
  readPreviewArrowEndpoints,
  rebuildPreviewArrowSvg,
  collectPreviewTextEditingGroups,
  bootstrapPreviewEditorRuntime,
  bootstrapPreviewEditorHost,
  ensurePreviewEditorState,
  ensurePreviewEngineShellCompatController,
  ensurePreviewElkPreviewController,
  extractPreviewDiagramOptionEntries,
  findPreviewEditableTextTarget,
  findPreviewTextBlockAtPoint,
  hasPreviewVisibleStylePicker,
  handlePreviewDoubleClickSelectionHost,
  initPreviewDiagramNavigation,
  initPreviewEditorRuntimeHost,
  initPreviewSaveClient,
  initPreviewShellCoordinator,
  formatPreviewDefinedStyleLabel,
  inferSelectionGap,
  inferPreviewStyleFromFields,
  inferPreviewStyleFromNode,
  isPreviewStructuralWrapper,
  isPreviewStyleableComponentType,
  isNudgeKey,
  isGridControlInputId,
  attemptPreviewDiagramNavigation,
  loadPreviewComponentTree,
  loadPreviewGridInfo,
  mergeRelativeOverrideEntries,
  normalizePreviewInspectorWidthUnit,
  normalizePreviewStyleFill,
  normalizePreviewStyleName,
  readPreviewArrowPointsHost,
  renderPreviewEmptyInspectorHost,
  renderPreviewBoxStyleOptions,
  renderPreviewMultiSelectionInspectorHost,
  renderPreviewMultiSelectionInspectorRuntimeHost,
  renderPreviewSelectionInspectorHost,
  renderPreviewSingleSelectionInspectorHost,
  renderPreviewSingleSelectionInspectorRuntimeHost,
  dispatchPreviewAlignSelectionHost,
  dispatchPreviewApplySelectionTargetsHost,
  dispatchPreviewDistributeSelectionHost,
  dispatchPreviewMultiFrameAlignHost,
  dispatchPreviewMultiFramePropHost,
  dispatchPreviewMultiFrameSizeHost,
  dispatchPreviewMultiStyleOverrideHost,
  dispatchPreviewSingleFrameAlignHost,
  dispatchPreviewSingleFramePropHost,
  dispatchPreviewSingleFrameSizeHost,
  normalizePreviewStyleStrokeOrBorder,
  normalizePreviewDiagramPath,
  pxToColSpan,
  pxToRowSpan,
  populatePreviewGridControlsHost,
  populatePreviewGridControls,
  patchPreviewFrameGroup,
  patchPreviewSvgFromLayout,
  previewTreeHasFrameId,
  readPreviewRenderedComponentBounds,
  resizeBoundsFromHandle,
  resolveBasePreviewStyleName,
  renderPreviewSingleSelectionInspector,
  resolvePreviewConstraintStatus,
  resolveEffectivePreviewStyleName,
  resolveMultiSelectionPreviewStyleState,
  resolveKeyboardShortcutAction,
  resolveSelectionAlignTargets,
  resolveSelectionDistributeTargets,
  resolvePreviewGridControlDomPatch,
  resolvePreviewGridControlState,
  resolvePreviewGridControlInputState,
  resolvePreviewGridControlRuntimeUpdateHost,
  resolvePreviewGridControlRuntimeUpdate,
  resolvePreviewGridControlStateFromDomState,
  resolvePreviewGridInfo,
  resolvePreviewGridInfoFromControlState,
  resolvePreviewGridInfoFromRuntimeState,
  resolvePreviewLayoutRelayoutStatus,
  resolvePreviewV3RelayoutStatus,
  resolvePreviewGridMarginsFromInputState,
  resolveSingleResizeOverride,
  resolveDoubleClickSelection,
  resolveAutolayoutReorderTarget,
  resolvePointerSelection,
  fitPreviewSvgToRenderedContent,
  resolvePreviewTextBlockRole,
  resolvePreviewTextEditCommit,
  resolvePreviewTextEditStartState,
  schedulePreviewTextEditCommitHost,
  startPreviewTextEditHost,
  suspendPreviewTextEditSelectionChromeHost,
  resolvePreviewTextEditorBlockStyle,
  resolvePreviewTextEditorSurface,
  resolvePrimarySelectedId,
  resolvePreviewResizeHandlePlan,
  resolvePreviewAutolayoutDragContext,
  normalizeSelectionGap,
  previewShellWidthToRem,
  readPreviewShellWidth,
  removePreviewWaypoint,
  renderMultiSelectionInspectorPanel,
  renderPreviewArrowWaypointHandles,
  renderPreviewWaypointHandlesHost,
  resolvePreviewArrowSvgUpdatePlan,
  resolvePreviewWaypointDragMove,
  resolvePreviewArrowWaypointHandlePositions,
  resolvePreviewArrowhead,
  resolvePreviewComponentSelectionState,
  renderPreviewTextLines,
  resolveSteppedPreviewDiagramUrl,
  resolvePreviewEditableComponentId,
  resolvePreviewRuntimeSizingValue,
  resolvePreviewShellCssLengthPx,
  resolvePreviewArrowShiftedSegments,
  resolvePreviewArrowSideShift,
  resolvePreviewArtboardFit,
  resolvePreviewDeleteCandidates,
  resolvePreviewDiagramRootFrameId,
  resolvePreviewDeleteTopLevelTargets,
  resolvePreviewDragSnap,
  resolvePreviewOverridePatchRestorePlan,
  resolvePreviewSerializedStateRestorePlan,
  resolveSingleSelectionAutolayoutPanelOptions,
  resolveSingleSelectionInspectorPanelRenderOptions,
  resolveSingleSelectionPreviewStyleState,
  resolvePreviewReflowShiftMap,
  renderSingleSelectionAutolayoutPanel,
  renderSingleSelectionInspectorPanel,
  resolvePreviewFrameSizePx,
  rebuildPreviewArrowSvgHost,
  removePreviewHandlesHost,
  restorePreviewOverrideEntries,
  restorePreviewOverridePatch,
  restorePreviewPropagatedResizeOverrides,
  restorePreviewSerializedState,
  installPreviewEditorTestFacadeHost,
  readPreviewGridControlStateFromDom,
  renderFreshPreviewSvg,
  renderPreviewFrameTreeToSvg,
  rowSpanToPx,
  renderPreviewReorderIndicator,
  renderPreviewTreeSelectionHost,
  renderPreviewTreePanel,
  renderPreviewGridOverlayHost,
  prunePreviewCollinearWaypoints,
  readPreviewStageCanvasDimensions,
  refreshPreviewGridInfoFromLayoutHost,
  refreshPreviewSceneHost,
  refreshPreviewTreeOverrideStateHost,
  rerenderPreviewStageFromModelHost,
  rerenderPreviewStageHost,
  runPreviewRelayout,
  snapshotNeedsPreviewRelayout,
  registerPreviewEditorDocumentBindingsHost,
  registerPreviewPageshowReload,
  restorePreviewSelectionIds,
  schedulePreviewLiveResizeRelayout,
  showPreviewResizeHandlesHost,
  showPreviewContextMenu,
  startPreviewResizeHost,
  startPreviewPointerInteractionHost,
  startPreviewWaypointDragHost,
  syncPreviewArrowModelFromFrameTree,
  syncPreviewBrowseLinksToPath,
  syncPreviewDiagramPickerToPath,
  syncPreviewConstraintStatus,
  syncPreviewSelectionUi,
  syncPreviewSvgHoverState,
  syncPreviewTreeOverrideState,
  syncPreviewTreeSelectionState,
  teardownPreviewStageSvgInteraction,
  collectPreviewRecursiveRelayoutEntries,
  createPreviewResizeStartState,
  dispatchPreviewWaypointDragMoveHost,
  shiftPreviewArrowheadPoints,
  markPreviewRelayoutExecution,
  runPreviewConstraintValidationHost,
  updatePreviewConstraintStatusHost,
  updatePreviewOverrideSummaryHost,
  updatePreviewArrowSvg,
  updatePreviewArrowVisualHost,
  writePreviewShellWidth,
} from './preview-shell/index.js';
export type {
  ApplyPreviewSvgOverridesOptions,
  ApplyPreviewSelectionStateSnapshotOptions,
  AttemptPreviewDiagramNavigationOptions,
  ClearPreviewSelectionStateOptions,
  PreviewArrowDelta,
  BootstrapPreviewEditorRuntimeOptions,
  PreviewBuildStatusUpdate,
  ConnectPreviewSseOptions,
  LoadPreviewComponentTreeOptions,
  LoadPreviewGridInfoOptions,
  LoadedPreviewGridInfoState,
  PreviewDiagramNavigationInitOptions,
  PreviewDiagramOptionEntry,
  PreviewLiveResizeOverrideEntry,
  PreviewLiveResizeOverrideMap,
  PreviewLiveResizeRelayoutRequest,
  PreviewLiveResizeRelayoutState,
  EditorSnapshot,
  EditorSnapshotInput,
  EditorOverridePatchCommand,
  EditorStatePatchCommand,
  EditorUndoCommand,
  EditorUndoStackOptions,
  PendingUndoableAction,
  EditorStateStoreDeps,
  EditorStateStoreOptions,
  InitPreviewOverrideToolbarOptions,
  PersistFrameKey,
  PreviewLayoutRelayoutRuntimeState,
  PreviewLayoutRelayoutStatus,
  PreviewRelayoutOverrideEntry,
  PreviewRelayoutResult,
  PreviewRelayoutStatus,
  PreviewV3RelayoutRuntimeState,
  PreviewV3RelayoutStatus,
  RelayoutFrameKey,
  InspectorSelectionItem,
  InspectorSelectionParentLayout,
  MultiSelectionInspectorViewModel,
  MultiSelectionAlignItem,
  MultiSelectionAlignState,
  MultiSelectionContainerItem,
  MultiSelectionContainerState,
  MultiSelectionInspectorResolvedState,
  MultiSelectionInspectorRuntimeItem,
  MultiSelectionInspectorPanelRenderOptions,
  MultiSelectionSizingItem,
  MultiSelectionSizingState,
  MultiSelectionStyleState,
  DispatchPreviewAlignSelectionHostOptions,
  DispatchPreviewApplySelectionTargetsHostOptions,
  DispatchPreviewDistributeSelectionHostOptions,
  DispatchPreviewMultiFrameAlignHostOptions,
  DispatchPreviewMultiFramePropHostOptions,
  DispatchPreviewMultiFrameSizeHostOptions,
  DispatchPreviewMultiStyleOverrideHostOptions,
  SelectionActionPlanItem,
  SelectionAlignMode,
  CollectPreviewSelectionActionInfoOptions,
  DoubleClickSelectionResolution,
  DragCompletionPlan,
  DragReorderTarget,
  PreviewAutolayoutDragContext,
  PreviewDragDelta,
  PreviewDragCompletionDispatchOptions,
  PreviewDragCompletionState,
  PreviewDragMoveDispatchOptions,
  PreviewDragMoveResult,
  PreviewDragMoveState,
  PreviewDragSnapResult,
  PreviewDragSnapTargets,
  PreviewHitNodeBounds,
  PreviewHitTestNode,
  PreviewHitTestOptions,
  InspectorDeltaState,
  InspectorDirection,
  InspectorEffectiveDeltaState,
  InspectorPositionType,
  InspectorSizingMode,
  PreviewAutolayoutInspectorNode,
  PreviewAutolayoutInspectorNodeData,
  SingleSelectionAutolayoutPanelRenderOptions,
  PreviewSizingAxis,
  PreviewArrowEndpointShift,
  PreviewArrowEndpoints,
  PreviewArrowPoint,
  PreviewArrowSegmentCoordinate,
  PreviewArrowSvgUpdatePlan,
  PreviewWaypointDragAxis,
  PreviewWaypointDragMoveResolution,
  PreviewWaypointDragState,
  PreviewArrowhead,
  PreviewStageCanvasDimensions,
  RerenderPreviewStageHostOptions,
  CreatePreviewEditorRuntimeSetFromRuntimeOptions,
  PreviewEditorStateApi,
  PreviewEditorStateInitOptions,
  PreviewEngineShellCompatControllerApi,
  PreviewEngineShellCompatControllerInitOptions,
  PreviewElkControllerApi,
  PreviewElkControllerInitOptions,
  PreviewEngineShellControllerInitOptions,
  PreviewEventSourceLike,
  PreviewPageshowReloadOptions,
  PreviewSaveClientApi,
  PreviewSaveClientInitConfig,
  PreviewSaveClientInitOptions,
  PreviewSaveClientRuntime,
  PreviewSaveClientRuntimeDeps,
  PreviewSaveClientRuntimeOptions,
  PreviewShellCoordinatorInitOptions,
  PreviewTextEditCommitResolution,
  PreviewTextEditStartState,
  PreviewTextEditorBlockStyle,
  PreviewTextEditorRole,
  PointerSelectionResolution,
  InteractionDeltaPatch,
  InteractionDeltaValue,
  InteractionOverrideEntry,
  KeyboardShortcutAction,
  LoadPreviewSvgOptions,
  MultiSelectionResizeMember,
  MultiSelectionResizeOverride,
  PreviewFallbackResponse,
  NudgeKey,
  NudgeSelectionItem,
  PreviewKeyboardDelta,
  DispatchPreviewKeyboardShortcutHostOptions,
  PreviewKeyboardDispatchOptions,
  DispatchPreviewDeleteFramesHostOptions,
  PreviewFrameTreeSeed,
  PreviewGridControlState,
  PreviewGridControlInputState,
  PreviewFrameMutationNode,
  PreviewFrameMutationNodeData,
  PreviewConstraintStatus,
  PreviewConstraintSummary,
  CreatePreviewOverrideToolbarHostOptions,
  PreviewInspectorArrowNode,
  PreviewInspectorGridInfo,
  DispatchPreviewSingleFrameAlignHostOptions,
  DispatchPreviewSingleFramePropHostOptions,
  DispatchPreviewSingleFrameSizeHostOptions,
  PreviewFrameOverrideEntry,
  PreviewFrameOverrideMap,
  PreviewFramePropMutationKind,
  PreviewFramePropMutationResult,
  PreviewFrameSizeDimension,
  PreviewOverrideExportEntry,
  PreviewOverrideBoxStylePreset,
  PreviewOverrideDelta,
  PreviewOverrideEntry,
  PreviewOverridePatchRestorePlan,
  PreviewOverrideRelayoutStatus,
  PreviewOverrideRootNode,
  PreviewOverrideTreeNode,
  PreviewRestoreNode,
  PreviewRenderedStyleFields,
  PreviewGridInfoState,
  PreviewGridInfo,
  PreviewGridOverlayLine,
  PreviewGridOverlayRect,
  PreviewGridOverlayScene,
  PreviewSceneHostShape,
  PreviewGridOverlayShape,
  PreviewLoadCanonicalState,
  PreviewLoadExecutionMode,
  PreviewLoadInvocationOptions,
  PreviewLoadNormalizedOptions,
  PreviewLoadRenderResult,
  PreviewLocalRelayoutStatus,
  PreviewStyleMode,
  PreviewStyleNode,
  PreviewStyleNodeData,
  PreviewStyleOverrideEntry,
  PreviewStyleOverrideMap,
  PreviewShellTreeEntry,
  PreviewShellTreeNode,
  PreviewSingleSelectionInspectorNode,
  PreviewStageInteractionHandlers,
  BindPreviewStageSvgInteractionHostOptions,
  DispatchPreviewStageSvgHoverHostOptions,
  DispatchPreviewStageSvgHoverOutHostOptions,
  RunPreviewRelayoutOptions,
  ReorderResolution,
  ReorderTargetPoint,
  RenderPreviewSingleSelectionInspectorOptions,
  RenderPreviewTreePanelOptions,
  ResolvePreviewGridInfoParams,
  ResizePersistenceEntry,
  ResizePersistenceItem,
  ResizePersistencePlan,
  SchedulePreviewLiveResizeRelayoutOptions,
  ResizeCompletionPlan,
  PreviewResizeCompletionDispatchOptions,
  PreviewResizeCompletionState,
  PreviewResizeMoveDispatchOptions,
  PreviewResizeMoveResult,
  PreviewResizeMoveState,
  PreviewResizeNodeBounds,
  PreviewResizeSelection,
  BindPreviewStageSvgInteractionOptions,
  ResizeBounds,
  ResizeBoundsInput,
  ResizeGuideLine,
  RestorePreviewOverridePatchOptions,
  RestorePreviewSerializedStateOptions,
  SingleResizeOverride,
  SingleResizeOverrideInput,
  SelectionActionInfo,
  SelectionDistributeAxis,
  SelectionParentBounds,
  PreviewSelectionActionInfo,
  PreviewSelectionActionItem,
  PreviewSelectionActionNode,
  PreviewSelectionActionNodeData,
  PreviewSelectionDelta,
  ShowPreviewContextMenuAction,
  ShowPreviewContextMenuOptions,
  SelectionStateMutation,
  SelectionStateSnapshot,
  SelectionTargetOverrideEntry,
  SelectionTargetPoint,
  PreviewArtboardBounds,
  PreviewArtboardNode,
  PreviewArtboardViewBox,
  BindPreviewGridControlsOptions,
  ResolvePreviewDiagramRootFrameIdOptions,
  ClampPreviewDragDeltaWithinParentOptions,
  CompletePreviewDragInteractionOptions,
  DispatchPreviewGridControlChangeOptions,
  PreviewFrameDeleteNode,
  PreviewSnapComputation,
  PreviewSnapRect,
  PreviewSnapTargets,
  CompletePreviewResizeInteractionOptions,
  PersistPreviewResizeToFrameOverridesOptions,
  PopulatePreviewGridControlsOptions,
  PreviewGridControlChangeDispatchResult,
  PreviewGridHostControlElement,
  PreviewGridSelectionBindingOptions,
  PreviewResizePersistNode,
  PreviewDragClampDelta,
  PreviewDragClampNode,
  PreviewDragClampParentNode,
  PreviewCanonicalArrowState,
  PreviewCanonicalDocumentState,
  PreviewCanonicalFrameTreeState,
  PreviewComponentTreeLoadMode,
  PreviewDiagramBootstrapState,
  PreviewDiagramTreeModel,
  PreviewGridInfoFallbackMetrics,
  PreviewGridInfoLoadMode,
  PreviewJsonFetchResponse,
  FreshPreviewDocument,
  FreshPreviewSvgRenderResult,
  ReadPreviewGridControlStateFromDomOptions,
  RenderFreshPreviewSvgOptions,
  RenderPreviewFrameTreeToSvgOptions,
  ResolvePreviewGridInfoOptions,
  SingleSelectionAutolayoutState,
  SingleSelectionInspectorViewModel,
  SingleSelectionInspectorPanelRenderOptions,
  SingleSelectionInspectorViolation,
  SingleSelectionPreviewStyleState,
  MultiSelectionPreviewStyleItem,
  MultiSelectionPreviewStyleState,
  PreviewSerializedStateRestorePlan,
  RenderPreviewTreeSelectionHostOptions,
  RenderPreviewGridOverlayHostOptions,
  RefreshPreviewGridInfoFromLayoutHostOptions,
  RefreshPreviewSceneHostOptions,
  ResolvePreviewLayoutRelayoutStatusOptions,
  ResolvePreviewV3RelayoutStatusOptions,
  ResolvePreviewComponentSelectionStateOptions,
  SyncPreviewSelectionUiOptions,
  SyncPreviewArrowModelFromFrameTreeOptions,
  DispatchPreviewRelayoutFailureHostOptions,
  DispatchPreviewRelayoutSuccessHostOptions,
  IsPreviewFrameManagedTargetOptions,
  UpdatePreviewConstraintStatusHostOptions,
  UpdatePreviewOverrideSummaryHostOptions,
  RunPreviewConstraintValidationHostOptions,
  ApplyPreviewWaypointOverridesHostOptions,
} from './preview-shell/index.js';

export {
  serializeFrameDiagram,
  serializeFrame,
  deserializeFrameWire,
  deserializeFrameDiagramWire,
} from './frame-serialize.js';

export {
  createPreviewElkLayoutControlsRuntime,
  createPreviewElkShellControllerRuntime,
  ELK_LAYERED_PREVIEW_ENGINE,
  FORCE_PREVIEW_ENGINE,
  FORCE_PREVIEW_PARAM_SPECS,
  SEQUENCE_PREVIEW_ENGINE,
  PREVIEW_ENGINE_REGISTRY,
  elkLayeredPreviewControlSpecs,
  getPreviewEngine,
  listPreviewEnginesBySidebarSection,
  listPreviewEngines,
  registerPreviewEngine,
  renderPreviewElkDebugOverlay,
  renderPreviewElkRawView,
  resolvePreviewEngine,
  serializePreviewEngineManifest,
} from './preview-engine/index.js';
export type {
  PreviewControlKind,
  PreviewControlSpec,
  PreviewEngineApiRoutes,
  PreviewEngineCapabilities,
  PreviewEngineContext,
  PreviewEngineManifest,
  PreviewShellMode,
} from './preview-engine/index.js';

/**
 * Spec 044 pilot namespace aliases.
 *
 * These objects prove the staged browser contract can exist under the current
 * global without breaking root-level compatibility. Consumers migrate to these
 * concern-owned groups first; root-level aliases stay temporarily.
 */
export const previewShell = Object.freeze({
  bootstrap: Object.freeze({
    attemptPreviewDiagramNavigation: previewShellRuntime.attemptPreviewDiagramNavigation,
    createPreviewEditorBootstrapFacadeFromEditorHost:
      previewShellRuntime.createPreviewEditorBootstrapFacadeFromEditorHost,
    createPreviewEditorBootstrapFacadeFromRuntime:
      previewShellRuntime.createPreviewEditorBootstrapFacadeFromRuntime,
    createLoadPreviewSvgHostOptionsFromRuntime:
      previewShellRuntime.createLoadPreviewSvgHostOptionsFromRuntime,
    createLoadPreviewSvgHostOptions: previewShellRuntime.createLoadPreviewSvgHostOptions,
    loadPreviewSvg: previewShellRuntime.loadPreviewSvg,
    loadPreviewComponentTree: previewShellRuntime.loadPreviewComponentTree,
    loadPreviewGridInfo: previewShellRuntime.loadPreviewGridInfo,
    initPreviewShellCoordinator: previewShellRuntime.initPreviewShellCoordinator,
    initPreviewOverrideToolbar: previewShellRuntime.initPreviewOverrideToolbar,
    normalizePreviewDiagramPath: previewShellRuntime.normalizePreviewDiagramPath,
    syncPreviewArrowModelFromFrameTree: previewShellRuntime.syncPreviewArrowModelFromFrameTree,
    syncPreviewBrowseLinksToPath: previewShellRuntime.syncPreviewBrowseLinksToPath,
    createPreviewDiagramLoadSignalState: previewShellRuntime.createPreviewDiagramLoadSignalState,
    signalPreviewDiagramLoaded: previewShellRuntime.signalPreviewDiagramLoaded,
    whenPreviewDiagramLoaded: previewShellRuntime.whenPreviewDiagramLoaded,
    createPreviewEditorInteractionFacadeFromEditorHost:
      previewShellRuntime.createPreviewEditorInteractionFacadeFromEditorHost,
    createPreviewEditorInteractionFacadeFromBrowserHost:
      previewShellRuntime.createPreviewEditorInteractionFacadeFromBrowserHost,
    createPreviewEditorInteractionFacadeFromRuntime:
      previewShellRuntime.createPreviewEditorInteractionFacadeFromRuntime,
    createPreviewGridEditorBrowserStateFromBrowserHost:
      previewShellRuntime.createPreviewGridEditorBrowserStateFromBrowserHost,
    createPreviewGridEditorInstallUnitFromEditorHost:
      previewShellRuntime.createPreviewGridEditorInstallUnitFromEditorHost,
    createPreviewGridEditorInstallUnitFromBrowserHost:
      previewShellRuntime.createPreviewGridEditorInstallUnitFromBrowserHost,
    createPreviewGridEditorRuntimeFromBrowserHost:
      previewShellRuntime.createPreviewGridEditorRuntimeFromBrowserHost,
    createPreviewEditorRuntimeSetFromEditorHost:
      previewShellRuntime.createPreviewEditorRuntimeSetFromEditorHost,
    createPreviewEditorRuntimeSetFromRuntime:
      previewShellRuntime.createPreviewEditorRuntimeSetFromRuntime,
    createPreviewEditorRuntimeSetFromHost: previewShellRuntime.createPreviewEditorRuntimeSetFromHost,
    createPreviewEditorRuntimeSet: previewShellRuntime.createPreviewEditorRuntimeSet,
    createBootstrapPreviewEditorRuntimeOptionsFromHost:
      previewShellRuntime.createBootstrapPreviewEditorRuntimeOptionsFromHost,
    createBootstrapPreviewEditorHostOptionsFromRuntime:
      previewShellRuntime.createBootstrapPreviewEditorHostOptionsFromRuntime,
    createPreviewBuildStatusUpdater: previewShellRuntime.createPreviewBuildStatusUpdater,
    createPreviewOverrideToolbarHostOptions:
      previewShellRuntime.createPreviewOverrideToolbarHostOptions,
    createPreviewSaveClientRuntime: previewShellRuntime.createPreviewSaveClientRuntime,
    createPreviewSaveClientInitConfig: previewShellRuntime.createPreviewSaveClientInitConfig,
    collectPreviewEngineSavePayload: previewShellRuntime.collectPreviewEngineSavePayload,
    initPreviewSaveClient: previewShellRuntime.initPreviewSaveClient,
    initPreviewEditorRuntimeHost: previewShellRuntime.initPreviewEditorRuntimeHost,
    bootstrapPreviewEditorRuntime: previewShellRuntime.bootstrapPreviewEditorRuntime,
    bootstrapPreviewEditorHost: previewShellRuntime.bootstrapPreviewEditorHost,
    ensurePreviewEditorState: previewShellRuntime.ensurePreviewEditorState,
    ensurePreviewEngineShellCompatController:
      previewShellRuntime.ensurePreviewEngineShellCompatController,
    ensurePreviewEngineShellController: previewShellRuntime.ensurePreviewEngineShellController,
    ensurePreviewElkPreviewController: previewShellRuntime.ensurePreviewElkPreviewController,
    getPreviewEngineShellController: previewShellRuntime.getPreviewEngineShellController,
    initPreviewEngineShellPanel: previewShellRuntime.initPreviewEngineShellPanel,
    isPreviewEngineShellLayoutActive: previewShellRuntime.isPreviewEngineShellLayoutActive,
    connectPreviewSse: previewShellRuntime.connectPreviewSse,
    createPreviewEditorSceneFacadeFromRuntime:
      previewShellRuntime.createPreviewEditorSceneFacadeFromRuntime,
    registerPreviewEditorDocumentBindingsHost: previewShellRuntime.registerPreviewEditorDocumentBindingsHost,
    installPreviewEditorTestFacadeHost: previewShellRuntime.installPreviewEditorTestFacadeHost,
    registerPreviewPageshowReload: previewShellRuntime.registerPreviewPageshowReload,
    restorePreviewSelectionIds: previewShellRuntime.restorePreviewSelectionIds,
    createEditorStateStore: previewShellRuntime.createEditorStateStore,
    captureEditorSnapshot: previewShellRuntime.captureEditorSnapshot,
    cloneEditorSnapshotValue: previewShellRuntime.cloneEditorSnapshotValue,
    normalizeGridOverrides: previewShellRuntime.normalizeGridOverrides,
    parseEditorSnapshot: previewShellRuntime.parseEditorSnapshot,
    serializeEditorSnapshot: previewShellRuntime.serializeEditorSnapshot,
    captureOverrideEntries: previewShellRuntime.captureOverrideEntries,
    createOverridePatchCommand: previewShellRuntime.createOverridePatchCommand,
    createStatePatchCommand: previewShellRuntime.createStatePatchCommand,
    overridePatchChanged: previewShellRuntime.overridePatchChanged,
  }),
  inspector: Object.freeze({
    bindPreviewInspectorActions: previewShellRuntime.bindPreviewInspectorActions,
    applyMultiFramePropMutation: previewShellRuntime.applyMultiFramePropMutation,
    applyMultiFrameSizeMutation: previewShellRuntime.applyMultiFrameSizeMutation,
    applySingleFramePropMutation: previewShellRuntime.applySingleFramePropMutation,
    applySingleFrameSizeMutation: previewShellRuntime.applySingleFrameSizeMutation,
    applyVisiblePreviewStyleOverride: previewShellRuntime.applyVisiblePreviewStyleOverride,
    createPreviewInspectorDisplayRuntime: previewShellRuntime.createPreviewInspectorDisplayRuntime,
    createPreviewInspectorMutationRuntime: previewShellRuntime.createPreviewInspectorMutationRuntime,
    createPreviewInspectorSelectionRuntime: previewShellRuntime.createPreviewInspectorSelectionRuntime,
    bindPreviewEditorInspectorActionsFromBrowserHost:
      previewShellRuntime.bindPreviewEditorInspectorActionsFromBrowserHost,
    isPreviewStyleableComponentType: previewShellRuntime.isPreviewStyleableComponentType,
    normalizePreviewInspectorWidthUnit: previewShellRuntime.normalizePreviewInspectorWidthUnit,
    normalizePreviewStyleName: previewShellRuntime.normalizePreviewStyleName,
    formatPreviewDefinedStyleLabel: previewShellRuntime.formatPreviewDefinedStyleLabel,
    dispatchPreviewAlignSelectionHost: previewShellRuntime.dispatchPreviewAlignSelectionHost,
    dispatchPreviewApplySelectionTargetsHost: previewShellRuntime.dispatchPreviewApplySelectionTargetsHost,
    dispatchPreviewDistributeSelectionHost: previewShellRuntime.dispatchPreviewDistributeSelectionHost,
    dispatchPreviewMultiFrameAlignHost: previewShellRuntime.dispatchPreviewMultiFrameAlignHost,
    dispatchPreviewMultiFramePropHost: previewShellRuntime.dispatchPreviewMultiFramePropHost,
    dispatchPreviewMultiFrameSizeHost: previewShellRuntime.dispatchPreviewMultiFrameSizeHost,
    dispatchPreviewMultiStyleOverrideHost: previewShellRuntime.dispatchPreviewMultiStyleOverrideHost,
    dispatchPreviewSingleFrameAlignHost: previewShellRuntime.dispatchPreviewSingleFrameAlignHost,
    dispatchPreviewSingleFramePropHost: previewShellRuntime.dispatchPreviewSingleFramePropHost,
    dispatchPreviewSingleFrameSizeHost: previewShellRuntime.dispatchPreviewSingleFrameSizeHost,
    renderPreviewEmptyInspectorHost: previewShellRuntime.renderPreviewEmptyInspectorHost,
    renderPreviewBoxStyleOptions: previewShellRuntime.renderPreviewBoxStyleOptions,
    renderPreviewMultiSelectionInspectorHost: previewShellRuntime.renderPreviewMultiSelectionInspectorHost,
    renderPreviewMultiSelectionInspectorRuntimeHost: previewShellRuntime.renderPreviewMultiSelectionInspectorRuntimeHost,
    renderPreviewSelectionInspectorHost: previewShellRuntime.renderPreviewSelectionInspectorHost,
    renderPreviewSingleSelectionInspector: previewShellRuntime.renderPreviewSingleSelectionInspector,
    renderPreviewSingleSelectionInspectorHost: previewShellRuntime.renderPreviewSingleSelectionInspectorHost,
    renderPreviewSingleSelectionInspectorRuntimeHost: previewShellRuntime.renderPreviewSingleSelectionInspectorRuntimeHost,
    renderMultiSelectionInspectorPanel: previewShellRuntime.renderMultiSelectionInspectorPanel,
    completePreviewTextEdit: previewShellRuntime.completePreviewTextEdit,
    cancelPreviewTextEdit: previewShellRuntime.cancelPreviewTextEdit,
    schedulePreviewTextEditCommitHost: previewShellRuntime.schedulePreviewTextEditCommitHost,
    startPreviewTextEditHost: previewShellRuntime.startPreviewTextEditHost,
    suspendPreviewTextEditSelectionChromeHost:
      previewShellRuntime.suspendPreviewTextEditSelectionChromeHost,
    collectPreviewTextEditingGroups: previewShellRuntime.collectPreviewTextEditingGroups,
    findPreviewEditableTextTarget: previewShellRuntime.findPreviewEditableTextTarget,
    resolvePreviewEditableComponentId: previewShellRuntime.resolvePreviewEditableComponentId,
    resolveMultiSelectionInspectorState: previewShellRuntime.resolveMultiSelectionInspectorState,
    resolveMultiSelectionPreviewStyleState: previewShellRuntime.resolveMultiSelectionPreviewStyleState,
    resolvePreviewFrameSizePx: previewShellRuntime.resolvePreviewFrameSizePx,
    resolvePreviewTextEditStartState: previewShellRuntime.resolvePreviewTextEditStartState,
  }),
  interaction: Object.freeze({
    applyPreviewSelectionStateSnapshot: previewShellRuntime.applyPreviewSelectionStateSnapshot,
    clearPreviewSelectionState: previewShellRuntime.clearPreviewSelectionState,
    createPreviewSelectionRuntime: previewShellRuntime.createPreviewSelectionRuntime,
    applySelectionStateMutation: previewShellRuntime.applySelectionStateMutation,
    applyReorderOrder: previewShellRuntime.applyReorderOrder,
    bindPreviewArrowSegmentInsertHandles: previewShellRuntime.bindPreviewArrowSegmentInsertHandles,
    bindPreviewStageSvgInteractionHost: previewShellRuntime.bindPreviewStageSvgInteractionHost,
    bindPreviewStageSvgInteraction: previewShellRuntime.bindPreviewStageSvgInteraction,
    clampPreviewDragDeltaWithinParent: previewShellRuntime.clampPreviewDragDeltaWithinParent,
    clearPreviewReorderIndicator: previewShellRuntime.clearPreviewReorderIndicator,
    clearPreviewSvgHoverState: previewShellRuntime.clearPreviewSvgHoverState,
    collectPreviewSnapTargets: previewShellRuntime.collectPreviewSnapTargets,
    collectPreviewMultiResizeSelection: previewShellRuntime.collectPreviewMultiResizeSelection,
    collectPreviewSelectionActionInfo: previewShellRuntime.collectPreviewSelectionActionInfo,
    commitPreviewWaypointInsert: previewShellRuntime.commitPreviewWaypointInsert,
    commitPreviewWaypointRemoval: previewShellRuntime.commitPreviewWaypointRemoval,
    collectPreviewRecursiveRelayoutEntries: previewShellRuntime.collectPreviewRecursiveRelayoutEntries,
    createPreviewResizeStartState: previewShellRuntime.createPreviewResizeStartState,
    dispatchPreviewDragMove: previewShellRuntime.dispatchPreviewDragMove,
    deletePreviewSelectedFramesHost: previewShellRuntime.deletePreviewSelectedFramesHost,
    dispatchPreviewDeleteFramesHost: previewShellRuntime.dispatchPreviewDeleteFramesHost,
    dispatchPreviewDeleteFrames: previewShellRuntime.dispatchPreviewDeleteFrames,
    dispatchPreviewKeyboardShortcut: previewShellRuntime.dispatchPreviewKeyboardShortcut,
    dispatchPreviewDragMoveHost: previewShellRuntime.dispatchPreviewDragMoveHost,
    dispatchPreviewResizeMove: previewShellRuntime.dispatchPreviewResizeMove,
    dispatchPreviewResizeMoveHost: previewShellRuntime.dispatchPreviewResizeMoveHost,
    dispatchPreviewWaypointDragMoveHost: previewShellRuntime.dispatchPreviewWaypointDragMoveHost,
    completePreviewDragInteraction: previewShellRuntime.completePreviewDragInteraction,
    completePreviewResizeInteraction: previewShellRuntime.completePreviewResizeInteraction,
    completePreviewWaypointDragInteraction: previewShellRuntime.completePreviewWaypointDragInteraction,
    createPreviewArrowWaypointRuntime: previewShellRuntime.createPreviewArrowWaypointRuntime,
    createPreviewKeyboardRuntime: previewShellRuntime.createPreviewKeyboardRuntime,
    createPreviewKeyboardRuntimeFromHost:
      previewShellRuntime.createPreviewKeyboardRuntimeFromHost,
    createPreviewPointerInteractionRuntimeFromHost:
      previewShellRuntime.createPreviewPointerInteractionRuntimeFromHost,
    createPreviewPointerInteractionRuntime: previewShellRuntime.createPreviewPointerInteractionRuntime,
    createPreviewResizeInteractionRuntime:
      previewShellRuntime.createPreviewResizeInteractionRuntime,
    createPreviewResizeInteractionRuntimeFromHost:
      previewShellRuntime.createPreviewResizeInteractionRuntimeFromHost,
    createPreviewTextEditRuntime: previewShellRuntime.createPreviewTextEditRuntime,
    createPreviewTextEditRuntimeFromHost:
      previewShellRuntime.createPreviewTextEditRuntimeFromHost,
    createPreviewSelectionChromeRuntimeFromHost:
      previewShellRuntime.createPreviewSelectionChromeRuntimeFromHost,
    createPreviewSelectionChromeRuntime: previewShellRuntime.createPreviewSelectionChromeRuntime,
    createPreviewStageBindingRuntimeFromHost:
      previewShellRuntime.createPreviewStageBindingRuntimeFromHost,
    createPreviewStageBindingRuntime: previewShellRuntime.createPreviewStageBindingRuntime,
    createSelectionTargetOverrideEntries: previewShellRuntime.createSelectionTargetOverrideEntries,
    createPreviewDragStartState: previewShellRuntime.createPreviewDragStartState,
    createPreviewWaypointDragState: previewShellRuntime.createPreviewWaypointDragState,
    findPreviewArrowAtPoint: previewShellRuntime.findPreviewArrowAtPoint,
    findDeepestPreviewComponent: previewShellRuntime.findDeepestPreviewComponent,
    findPreviewComponentAtDepth: previewShellRuntime.findPreviewComponentAtDepth,
    handlePreviewDoubleClickSelectionHost: previewShellRuntime.handlePreviewDoubleClickSelectionHost,
    isAutolayoutParentLayout: previewShellRuntime.isAutolayoutParentLayout,
    normalizeSelectionGap: previewShellRuntime.normalizeSelectionGap,
    readPreviewArrowPointsHost: previewShellRuntime.readPreviewArrowPointsHost,
    renderPreviewArrowWaypointHandles: previewShellRuntime.renderPreviewArrowWaypointHandles,
    renderPreviewWaypointHandlesHost: previewShellRuntime.renderPreviewWaypointHandlesHost,
    renderPreviewReorderIndicator: previewShellRuntime.renderPreviewReorderIndicator,
    removePreviewHandlesHost: previewShellRuntime.removePreviewHandlesHost,
    resolveAutolayoutReorderTarget: previewShellRuntime.resolveAutolayoutReorderTarget,
    resolvePreviewDragSnap: previewShellRuntime.resolvePreviewDragSnap,
    resolveDoubleClickSelection: previewShellRuntime.resolveDoubleClickSelection,
    resolvePointerSelection: previewShellRuntime.resolvePointerSelection,
    renderPreviewTreeSelectionHost: previewShellRuntime.renderPreviewTreeSelectionHost,
    resolvePreviewAutolayoutDragContext: previewShellRuntime.resolvePreviewAutolayoutDragContext,
    resolvePreviewComponentSelectionState: previewShellRuntime.resolvePreviewComponentSelectionState,
    resolvePreviewResizeHandlePlan: previewShellRuntime.resolvePreviewResizeHandlePlan,
    resolvePreviewWaypointDragMove: previewShellRuntime.resolvePreviewWaypointDragMove,
    restorePreviewPropagatedResizeOverrides: previewShellRuntime.restorePreviewPropagatedResizeOverrides,
    resolvePrimarySelectedId: previewShellRuntime.resolvePrimarySelectedId,
    resolveSelectionAlignTargets: previewShellRuntime.resolveSelectionAlignTargets,
    resolveSelectionDistributeTargets: previewShellRuntime.resolveSelectionDistributeTargets,
    resolvePreviewDiagramRootFrameId: previewShellRuntime.resolvePreviewDiagramRootFrameId,
    showPreviewContextMenu: previewShellRuntime.showPreviewContextMenu,
    showPreviewResizeHandlesHost: previewShellRuntime.showPreviewResizeHandlesHost,
    startPreviewPointerInteractionHost: previewShellRuntime.startPreviewPointerInteractionHost,
    startPreviewResizeHost: previewShellRuntime.startPreviewResizeHost,
    startPreviewWaypointDragHost: previewShellRuntime.startPreviewWaypointDragHost,
    syncPreviewSelectionUi: previewShellRuntime.syncPreviewSelectionUi,
    syncPreviewSvgHoverState: previewShellRuntime.syncPreviewSvgHoverState,
    updatePreviewArrowVisualHost: previewShellRuntime.updatePreviewArrowVisualHost,
    rebuildPreviewArrowSvgHost: previewShellRuntime.rebuildPreviewArrowSvgHost,
  }),
  scene: Object.freeze({
    applyPreviewWaypointOverridesHost: previewShellRuntime.applyPreviewWaypointOverridesHost,
    bindPreviewGridControls: previewShellRuntime.bindPreviewGridControls,
    createPreviewEditorSceneFacadeFromEditorHost:
      previewShellRuntime.createPreviewEditorSceneFacadeFromEditorHost,
    createPreviewEditorSceneFacadeFromRuntime:
      previewShellRuntime.createPreviewEditorSceneFacadeFromRuntime,
    createPreviewGridRuntimeFromEditorHost:
      previewShellRuntime.createPreviewGridRuntimeFromEditorHost,
    createPreviewGridRuntimeHost: previewShellRuntime.createPreviewGridRuntimeHost,
    cyclePreviewGuideModeHost: previewShellRuntime.cyclePreviewGuideModeHost,
    createPreviewGridOverlayScene: previewShellRuntime.createPreviewGridOverlayScene,
    dispatchPreviewGridControlChangeHost: previewShellRuntime.dispatchPreviewGridControlChangeHost,
    populatePreviewGridControls: previewShellRuntime.populatePreviewGridControls,
    populatePreviewGridControlsHost: previewShellRuntime.populatePreviewGridControlsHost,
    readPreviewGridControlStateFromDom: previewShellRuntime.readPreviewGridControlStateFromDom,
    dispatchPreviewGridControlChange: previewShellRuntime.dispatchPreviewGridControlChange,
    readPreviewStageCanvasDimensions: previewShellRuntime.readPreviewStageCanvasDimensions,
    refreshPreviewGridInfoFromLayoutHost: previewShellRuntime.refreshPreviewGridInfoFromLayoutHost,
    refreshPreviewSceneHost: previewShellRuntime.refreshPreviewSceneHost,
    refreshPreviewTreeOverrideStateHost: previewShellRuntime.refreshPreviewTreeOverrideStateHost,
    rerenderPreviewStageFromModelHost: previewShellRuntime.rerenderPreviewStageFromModelHost,
    rerenderPreviewStageHost: previewShellRuntime.rerenderPreviewStageHost,
    renderPreviewGridOverlayHost: previewShellRuntime.renderPreviewGridOverlayHost,
    resolvePreviewGridControlRuntimeUpdateHost: previewShellRuntime.resolvePreviewGridControlRuntimeUpdateHost,
    resolvePreviewGridControlRuntimeUpdate: previewShellRuntime.resolvePreviewGridControlRuntimeUpdate,
    resolvePreviewGridInfo: previewShellRuntime.resolvePreviewGridInfo,
    resolvePreviewGridInfoFromRuntimeState: previewShellRuntime.resolvePreviewGridInfoFromRuntimeState,
    renderPreviewTreePanel: previewShellRuntime.renderPreviewTreePanel,
    syncPreviewTreeOverrideState: previewShellRuntime.syncPreviewTreeOverrideState,
    syncPreviewTreeSelectionState: previewShellRuntime.syncPreviewTreeSelectionState,
    runPreviewConstraintValidationHost: previewShellRuntime.runPreviewConstraintValidationHost,
    syncPreviewConstraintStatus: previewShellRuntime.syncPreviewConstraintStatus,
    updatePreviewConstraintStatusHost: previewShellRuntime.updatePreviewConstraintStatusHost,
    updatePreviewOverrideSummaryHost: previewShellRuntime.updatePreviewOverrideSummaryHost,
    formatPreviewOverrideSummary: previewShellRuntime.formatPreviewOverrideSummary,
  }),
});

export const core = Object.freeze({
  BODY_LINE_STEP,
  BODY_SIZE,
  GRID_GUTTER,
  ICON_SIZE,
  INSET,
  annotationTextToSpec,
  createLine,
  deserializeFrameDiagramWire,
  deserializeFrameWire,
  effectiveResolvedStrokeWidth,
  frameOwnedTextBlockGap,
  frameOwnedTextBlockRole,
  frameOwnedTextBlocks,
  layoutElkFrameDiagram,
  layoutFrameTree,
  layoutSequenceDiagram,
  renderSequenceDiagramToSvg,
  resolveStyles,
  routeArrows,
  sizeToPx,
  wrapTextLines,
});

export const previewBridge = Object.freeze({
  host: Object.freeze({
    applyFrameTreeRemovalsToPreviewTreeJson:
      previewShellRuntime.applyFrameTreeRemovalsToPreviewTreeJson,
    applyPreviewSessionRemovalsToDiagramJson:
      previewShellRuntime.applyPreviewSessionRemovalsToDiagramJson,
    createPreviewElkViewModeRuntimeFromBrowserHost:
      previewShellRuntime.createPreviewElkViewModeRuntimeFromBrowserHost,
    createPreviewElkViewModeRuntime: previewShellRuntime.createPreviewElkViewModeRuntime,
    createPreviewLayoutBridgeRuntimeFromBrowserHost:
      previewShellRuntime.createPreviewLayoutBridgeRuntimeFromBrowserHost,
    createPreviewLayoutBridgeRuntime: previewShellRuntime.createPreviewLayoutBridgeRuntime,
    createPreviewLayoutBridgeState: previewShellRuntime.createPreviewLayoutBridgeState,
    normalizePreviewLayoutBridgeLocalRelayoutOverrideMode:
      previewShellRuntime.normalizePreviewLayoutBridgeLocalRelayoutOverrideMode,
    resolvePreviewLayoutBridgeLocalRelayoutStatus:
      previewShellRuntime.resolvePreviewLayoutBridgeLocalRelayoutStatus,
    updatePreviewComponentModelFromLayout:
      previewShellRuntime.updatePreviewComponentModelFromLayout,
  }),
  relayout: Object.freeze({
    applyPreviewOverridesToFrameTree: previewShellRuntime.applyPreviewOverridesToFrameTree,
    collectPreviewRelayoutFrameOverrides: previewShellRuntime.collectPreviewRelayoutFrameOverrides,
    createPreviewEditorRelayoutFacadeFromEditorHost:
      previewShellRuntime.createPreviewEditorRelayoutFacadeFromEditorHost,
    createPreviewEditorRelayoutFacadeFromRuntime:
      previewShellRuntime.createPreviewEditorRelayoutFacadeFromRuntime,
    createPreviewRelayoutRuntimeFromRuntime:
      previewShellRuntime.createPreviewRelayoutRuntimeFromRuntime,
    createPreviewRelayoutRuntimeFromEditorHost:
      previewShellRuntime.createPreviewRelayoutRuntimeFromEditorHost,
    createPreviewRelayoutRuntime: previewShellRuntime.createPreviewRelayoutRuntime,
    createPreviewRelayoutRuntimeOptionsFromRuntime:
      previewShellRuntime.createPreviewRelayoutRuntimeOptionsFromRuntime,
    createPreviewRelayoutRuntimeOptionsFromHost:
      previewShellRuntime.createPreviewRelayoutRuntimeOptionsFromHost,
    createPreviewRelayoutRuntimeState: previewShellRuntime.createPreviewRelayoutRuntimeState,
    resolvePreviewLayoutRelayoutStatus: previewShellRuntime.resolvePreviewLayoutRelayoutStatus,
    resolvePreviewV3RelayoutStatus: previewShellRuntime.resolvePreviewV3RelayoutStatus,
    formatPreviewRelayoutStatusMessage: previewShellRuntime.formatPreviewRelayoutStatusMessage,
    markPreviewRelayoutExecution: previewShellRuntime.markPreviewRelayoutExecution,
    isPreviewFrameManagedTarget: previewShellRuntime.isPreviewFrameManagedTarget,
    runPreviewRelayout: previewShellRuntime.runPreviewRelayout,
    snapshotNeedsPreviewRelayout: previewShellRuntime.snapshotNeedsPreviewRelayout,
    restorePreviewOverrideEntries: previewShellRuntime.restorePreviewOverrideEntries,
    restorePreviewOverridePatch: previewShellRuntime.restorePreviewOverridePatch,
    restorePreviewSerializedState: previewShellRuntime.restorePreviewSerializedState,
    createPreviewLiveResizeRelayoutState: previewShellRuntime.createPreviewLiveResizeRelayoutState,
    createPreviewLiveResizeRuntimeFromHost:
      previewShellRuntime.createPreviewLiveResizeRuntimeFromHost,
    createPreviewLiveResizeRuntime: previewShellRuntime.createPreviewLiveResizeRuntime,
    schedulePreviewLiveResizeRelayout: previewShellRuntime.schedulePreviewLiveResizeRelayout,
    cancelPreviewLiveResizeRelayout: previewShellRuntime.cancelPreviewLiveResizeRelayout,
    createPreviewStateRestoreRuntimeFromEditorHost:
      previewShellRuntime.createPreviewStateRestoreRuntimeFromEditorHost,
    createPreviewStateRestoreRuntime: previewShellRuntime.createPreviewStateRestoreRuntime,
    dispatchPreviewClearOverride: previewShellRuntime.dispatchPreviewClearOverride,
    dispatchPreviewRelayoutFailureHost: previewShellRuntime.dispatchPreviewRelayoutFailureHost,
    dispatchPreviewRelayoutSuccessHost: previewShellRuntime.dispatchPreviewRelayoutSuccessHost,
    persistPreviewResizeToFrameOverrides: previewShellRuntime.persistPreviewResizeToFrameOverrides,
    collectRecursiveRelayoutEntries: previewShellRuntime.collectRecursiveRelayoutEntries,
    createOriginalOverrideEntries: previewShellRuntime.createOriginalOverrideEntries,
    mergeRelativeOverrideEntries: previewShellRuntime.mergeRelativeOverrideEntries,
    filterRelayoutOverrideEntry: previewShellRuntime.filterRelayoutOverrideEntry,
    hasPreviewRelayoutFrameOverride: previewShellRuntime.hasPreviewRelayoutFrameOverride,
    hasV3FrameOverride: previewShellRuntime.hasV3FrameOverride,
    clearPreviewCoercedOverrides: previewShellRuntime.clearPreviewCoercedOverrides,
    clearPreviewTransientLayoutOverrides: previewShellRuntime.clearPreviewTransientLayoutOverrides,
    collectPreviewCoercedKeys: previewShellRuntime.collectPreviewCoercedKeys,
  }),
  render: Object.freeze({
    applyPreviewSvgOverridesHost: previewShellRuntime.applyPreviewSvgOverridesHost,
    applyPreviewSvgOverrides: previewShellRuntime.applyPreviewSvgOverrides,
    readPreviewRenderedComponentBounds: previewShellRuntime.readPreviewRenderedComponentBounds,
    autoFitPreviewArtboard: previewShellRuntime.autoFitPreviewArtboard,
    collectPreviewFramesById: previewShellRuntime.collectPreviewFramesById,
    collectPreviewPlacedBounds: previewShellRuntime.collectPreviewPlacedBounds,
    fitPreviewSvgToRenderedContent: previewShellRuntime.fitPreviewSvgToRenderedContent,
    patchPreviewFrameGroup: previewShellRuntime.patchPreviewFrameGroup,
    patchPreviewSvgFromLayout: previewShellRuntime.patchPreviewSvgFromLayout,
    previewArrowComponentId: previewShellRuntime.previewArrowComponentId,
    routePreviewArrows: previewShellRuntime.routePreviewArrows,
    syncPreviewArrowsInModel: previewShellRuntime.syncPreviewArrowsInModel,
    createPreviewArrowSvgFragment: previewShellRuntime.createPreviewArrowSvgFragment,
    patchPreviewArrowSvg: previewShellRuntime.patchPreviewArrowSvg,
    readPreviewArrowEndpoints: previewShellRuntime.readPreviewArrowEndpoints,
    rebuildPreviewArrowSvg: previewShellRuntime.rebuildPreviewArrowSvg,
    renderFreshPreviewSvg: previewShellRuntime.renderFreshPreviewSvg,
    renderPreviewFrameTreeToSvg: previewShellRuntime.renderPreviewFrameTreeToSvg,
    updatePreviewArrowSvg: previewShellRuntime.updatePreviewArrowSvg,
  }),
});

export const previewEngines = Object.freeze({
  registry: Object.freeze({
    PREVIEW_ENGINE_REGISTRY,
    getPreviewEngine,
    listPreviewEnginesBySidebarSection,
    listPreviewEngines,
    registerPreviewEngine,
    resolvePreviewEngine,
    serializePreviewEngineManifest,
    runtime: previewEngineRuntime,
  }),
  elk: Object.freeze({
    ELK_LAYERED_PREVIEW_ENGINE,
    createPreviewElkLayoutControlsRuntime: previewEngineRuntime.createPreviewElkLayoutControlsRuntime,
    createPreviewElkShellControllerRuntime: previewEngineRuntime.createPreviewElkShellControllerRuntime,
    elkLayeredPreviewControlSpecs,
    ELK_LAYERED_PARAM_SPECS,
    elkParamGroups,
    renderPreviewElkDebugOverlay: previewEngineRuntime.renderPreviewElkDebugOverlay,
    renderPreviewElkRawView: previewEngineRuntime.renderPreviewElkRawView,
    ensurePreviewEngineShellController: previewShellRuntime.ensurePreviewEngineShellController,
    ensurePreviewElkPreviewController: previewShellRuntime.ensurePreviewElkPreviewController,
  }),
  force: Object.freeze({
    FORCE_PREVIEW_ENGINE,
    FORCE_PREVIEW_PARAM_SPECS,
    createInitialForceSnapshot,
    updateForceSimulationParams,
    exportForceSnapshot,
    exportForceAuthoredSpec,
    tickForceSimulation,
    applyForceNodePatch,
  }),
  sequence: Object.freeze({
    SEQUENCE_PREVIEW_ENGINE,
  }),
});
