import * as previewShellRuntime from './preview-shell/index.js';

/**
 * Concern-owned preview-shell browser contract groups.
 *
 * `browser-entry.ts` should expose these groups, not hand-assemble them inline.
 */
export const previewShell = Object.freeze({
  bootstrap: Object.freeze({
    attemptPreviewDiagramNavigation: previewShellRuntime.attemptPreviewDiagramNavigation,
    createPreviewEditorBootstrapFacadeFromEditorHost:
      previewShellRuntime.createPreviewEditorBootstrapFacadeFromEditorHost,
    createPreviewEditorBootstrapFacadeFromRuntime:
      previewShellRuntime.createPreviewEditorBootstrapFacadeFromRuntime,
    createLoadPreviewSvgHostOptionsFromRuntime:
      previewShellRuntime.createLoadPreviewSvgHostOptionsFromRuntime,
    createLoadPreviewSvgHostOptions: previewShellRuntime.createLoadPreviewSvgHostOptions,
    loadPreviewSvg: previewShellRuntime.loadPreviewSvg,
    loadPreviewComponentTree: previewShellRuntime.loadPreviewComponentTree,
    loadPreviewGridInfo: previewShellRuntime.loadPreviewGridInfo,
    initPreviewShellCoordinator: previewShellRuntime.initPreviewShellCoordinator,
    initPreviewOverrideToolbar: previewShellRuntime.initPreviewOverrideToolbar,
    canonicalizePreviewDiagramPath: previewShellRuntime.canonicalizePreviewDiagramPath,
    normalizePreviewDiagramPath: previewShellRuntime.normalizePreviewDiagramPath,
    syncPreviewDiagramPickerToPath: previewShellRuntime.syncPreviewDiagramPickerToPath,
    syncPreviewArrowModelFromFrameTree: previewShellRuntime.syncPreviewArrowModelFromFrameTree,
    syncPreviewBrowseLinksToPath: previewShellRuntime.syncPreviewBrowseLinksToPath,
    createPreviewDiagramLoadSignalState: previewShellRuntime.createPreviewDiagramLoadSignalState,
    signalPreviewDiagramLoaded: previewShellRuntime.signalPreviewDiagramLoaded,
    whenPreviewDiagramLoaded: previewShellRuntime.whenPreviewDiagramLoaded,
    createPreviewEditorInteractionFacadeFromEditorHost:
      previewShellRuntime.createPreviewEditorInteractionFacadeFromEditorHost,
    createPreviewEditorInteractionFacadeFromBrowserHost:
      previewShellRuntime.createPreviewEditorInteractionFacadeFromBrowserHost,
    createPreviewEditorInteractionFacadeFromRuntime:
      previewShellRuntime.createPreviewEditorInteractionFacadeFromRuntime,
    createPreviewGridEditorBrowserStateFromBrowserHost:
      previewShellRuntime.createPreviewGridEditorBrowserStateFromBrowserHost,
    createPreviewGridEditorInstallOptionsFromLegacyEditorHost:
      previewShellRuntime.createPreviewGridEditorInstallOptionsFromLegacyEditorHost,
    createPreviewGridEditorInstallUnitFromLegacyEditorHost:
      previewShellRuntime.createPreviewGridEditorInstallUnitFromLegacyEditorHost,
    createPreviewGridEditorInstallUnitFromEditorHost:
      previewShellRuntime.createPreviewGridEditorInstallUnitFromEditorHost,
    createPreviewGridEditorInstallUnitFromBrowserHost:
      previewShellRuntime.createPreviewGridEditorInstallUnitFromBrowserHost,
    createPreviewGridEditorRuntimeFromBrowserHost:
      previewShellRuntime.createPreviewGridEditorRuntimeFromBrowserHost,
    createPreviewEditorRuntimeSetFromEditorHost:
      previewShellRuntime.createPreviewEditorRuntimeSetFromEditorHost,
    createPreviewEditorRuntimeSetFromRuntime:
      previewShellRuntime.createPreviewEditorRuntimeSetFromRuntime,
    createPreviewEditorRuntimeSetFromHost: previewShellRuntime.createPreviewEditorRuntimeSetFromHost,
    createPreviewEditorRuntimeSet: previewShellRuntime.createPreviewEditorRuntimeSet,
    createBootstrapPreviewEditorRuntimeOptionsFromHost:
      previewShellRuntime.createBootstrapPreviewEditorRuntimeOptionsFromHost,
    createBootstrapPreviewEditorHostOptionsFromRuntime:
      previewShellRuntime.createBootstrapPreviewEditorHostOptionsFromRuntime,
    createPreviewBuildStatusUpdater: previewShellRuntime.createPreviewBuildStatusUpdater,
    createPreviewOverridePayload: previewShellRuntime.createPreviewOverridePayload,
    createPreviewOverrideToolbarHostOptions:
      previewShellRuntime.createPreviewOverrideToolbarHostOptions,
    createPreviewSaveClientRuntime: previewShellRuntime.createPreviewSaveClientRuntime,
    createPreviewSaveClientInitConfig: previewShellRuntime.createPreviewSaveClientInitConfig,
    collectPreviewEngineSavePayload: previewShellRuntime.collectPreviewEngineSavePayload,
    initPreviewSaveClient: previewShellRuntime.initPreviewSaveClient,
    initPreviewEditorRuntimeHost: previewShellRuntime.initPreviewEditorRuntimeHost,
    bootstrapPreviewEditorRuntime: previewShellRuntime.bootstrapPreviewEditorRuntime,
    bootstrapPreviewEditorHost: previewShellRuntime.bootstrapPreviewEditorHost,
    ensurePreviewEditorState: previewShellRuntime.ensurePreviewEditorState,
    ensurePreviewEngineShellCompatController:
      previewShellRuntime.ensurePreviewEngineShellCompatController,
    ensurePreviewEngineShellController: previewShellRuntime.ensurePreviewEngineShellController,
    ensurePreviewElkPreviewController: previewShellRuntime.ensurePreviewElkPreviewController,
    getPreviewEngineShellController: previewShellRuntime.getPreviewEngineShellController,
    initPreviewEngineShellPanel: previewShellRuntime.initPreviewEngineShellPanel,
    isPreviewEngineShellLayoutActive: previewShellRuntime.isPreviewEngineShellLayoutActive,
    connectPreviewSse: previewShellRuntime.connectPreviewSse,
    createPreviewEditorSceneFacadeFromRuntime:
      previewShellRuntime.createPreviewEditorSceneFacadeFromRuntime,
    registerPreviewEditorDocumentBindingsHost: previewShellRuntime.registerPreviewEditorDocumentBindingsHost,
    installPreviewEditorTestFacadeHost: previewShellRuntime.installPreviewEditorTestFacadeHost,
    registerPreviewPageshowReload: previewShellRuntime.registerPreviewPageshowReload,
    restorePreviewSelectionIds: previewShellRuntime.restorePreviewSelectionIds,
    createEditorStateStore: previewShellRuntime.createEditorStateStore,
    captureEditorSnapshot: previewShellRuntime.captureEditorSnapshot,
    cloneEditorSnapshotValue: previewShellRuntime.cloneEditorSnapshotValue,
    normalizeGridOverrides: previewShellRuntime.normalizeGridOverrides,
    parseEditorSnapshot: previewShellRuntime.parseEditorSnapshot,
    serializeEditorSnapshot: previewShellRuntime.serializeEditorSnapshot,
    captureOverrideEntries: previewShellRuntime.captureOverrideEntries,
    createOverridePatchCommand: previewShellRuntime.createOverridePatchCommand,
    createStatePatchCommand: previewShellRuntime.createStatePatchCommand,
    overridePatchChanged: previewShellRuntime.overridePatchChanged,
  }),
  inspector: Object.freeze({
    bindPreviewInspectorActions: previewShellRuntime.bindPreviewInspectorActions,
    applyMultiFramePropMutation: previewShellRuntime.applyMultiFramePropMutation,
    applyMultiFrameSizeMutation: previewShellRuntime.applyMultiFrameSizeMutation,
    applySingleFramePropMutation: previewShellRuntime.applySingleFramePropMutation,
    applySingleFrameSizeMutation: previewShellRuntime.applySingleFrameSizeMutation,
    applyVisiblePreviewStyleOverride: previewShellRuntime.applyVisiblePreviewStyleOverride,
    createPreviewInspectorDisplayRuntime: previewShellRuntime.createPreviewInspectorDisplayRuntime,
    createPreviewInspectorMutationRuntime: previewShellRuntime.createPreviewInspectorMutationRuntime,
    createPreviewInspectorSelectionRuntime: previewShellRuntime.createPreviewInspectorSelectionRuntime,
    bindPreviewEditorInspectorActionsFromBrowserHost:
      previewShellRuntime.bindPreviewEditorInspectorActionsFromBrowserHost,
    isPreviewStyleableComponentType: previewShellRuntime.isPreviewStyleableComponentType,
    normalizePreviewInspectorWidthUnit: previewShellRuntime.normalizePreviewInspectorWidthUnit,
    normalizePreviewStyleName: previewShellRuntime.normalizePreviewStyleName,
    formatPreviewDefinedStyleLabel: previewShellRuntime.formatPreviewDefinedStyleLabel,
    dispatchPreviewAlignSelectionHost: previewShellRuntime.dispatchPreviewAlignSelectionHost,
    dispatchPreviewApplySelectionTargetsHost: previewShellRuntime.dispatchPreviewApplySelectionTargetsHost,
    dispatchPreviewDistributeSelectionHost: previewShellRuntime.dispatchPreviewDistributeSelectionHost,
    dispatchPreviewMultiFrameAlignHost: previewShellRuntime.dispatchPreviewMultiFrameAlignHost,
    dispatchPreviewMultiFramePropHost: previewShellRuntime.dispatchPreviewMultiFramePropHost,
    dispatchPreviewMultiFrameSizeHost: previewShellRuntime.dispatchPreviewMultiFrameSizeHost,
    dispatchPreviewMultiStyleOverrideHost: previewShellRuntime.dispatchPreviewMultiStyleOverrideHost,
    dispatchPreviewSingleFrameAlignHost: previewShellRuntime.dispatchPreviewSingleFrameAlignHost,
    dispatchPreviewSingleFramePropHost: previewShellRuntime.dispatchPreviewSingleFramePropHost,
    dispatchPreviewSingleFrameSizeHost: previewShellRuntime.dispatchPreviewSingleFrameSizeHost,
    renderPreviewEmptyInspectorHost: previewShellRuntime.renderPreviewEmptyInspectorHost,
    renderPreviewBoxStyleOptions: previewShellRuntime.renderPreviewBoxStyleOptions,
    renderPreviewMultiSelectionInspectorHost: previewShellRuntime.renderPreviewMultiSelectionInspectorHost,
    renderPreviewMultiSelectionInspectorRuntimeHost: previewShellRuntime.renderPreviewMultiSelectionInspectorRuntimeHost,
    renderPreviewSelectionInspectorHost: previewShellRuntime.renderPreviewSelectionInspectorHost,
    renderPreviewSingleSelectionInspector: previewShellRuntime.renderPreviewSingleSelectionInspector,
    renderPreviewSingleSelectionInspectorHost: previewShellRuntime.renderPreviewSingleSelectionInspectorHost,
    renderPreviewSingleSelectionInspectorRuntimeHost: previewShellRuntime.renderPreviewSingleSelectionInspectorRuntimeHost,
    renderMultiSelectionInspectorPanel: previewShellRuntime.renderMultiSelectionInspectorPanel,
    completePreviewTextEdit: previewShellRuntime.completePreviewTextEdit,
    cancelPreviewTextEdit: previewShellRuntime.cancelPreviewTextEdit,
    schedulePreviewTextEditCommitHost: previewShellRuntime.schedulePreviewTextEditCommitHost,
    startPreviewTextEditHost: previewShellRuntime.startPreviewTextEditHost,
    suspendPreviewTextEditSelectionChromeHost:
      previewShellRuntime.suspendPreviewTextEditSelectionChromeHost,
    collectPreviewTextEditingGroups: previewShellRuntime.collectPreviewTextEditingGroups,
    findPreviewEditableTextTarget: previewShellRuntime.findPreviewEditableTextTarget,
    resolvePreviewEditableComponentId: previewShellRuntime.resolvePreviewEditableComponentId,
    resolveMultiSelectionInspectorState: previewShellRuntime.resolveMultiSelectionInspectorState,
    resolveMultiSelectionPreviewStyleState: previewShellRuntime.resolveMultiSelectionPreviewStyleState,
    resolvePreviewFrameSizePx: previewShellRuntime.resolvePreviewFrameSizePx,
    resolvePreviewTextEditStartState: previewShellRuntime.resolvePreviewTextEditStartState,
  }),
  interaction: Object.freeze({
    applyPreviewSelectionStateSnapshot: previewShellRuntime.applyPreviewSelectionStateSnapshot,
    clearPreviewSelectionState: previewShellRuntime.clearPreviewSelectionState,
    createPreviewSelectionRuntime: previewShellRuntime.createPreviewSelectionRuntime,
    applySelectionStateMutation: previewShellRuntime.applySelectionStateMutation,
    applyReorderOrder: previewShellRuntime.applyReorderOrder,
    bindPreviewArrowSegmentInsertHandles: previewShellRuntime.bindPreviewArrowSegmentInsertHandles,
    bindPreviewStageSvgInteractionHost: previewShellRuntime.bindPreviewStageSvgInteractionHost,
    bindPreviewStageSvgInteraction: previewShellRuntime.bindPreviewStageSvgInteraction,
    clampPreviewDragDeltaWithinParent: previewShellRuntime.clampPreviewDragDeltaWithinParent,
    clearPreviewReorderIndicator: previewShellRuntime.clearPreviewReorderIndicator,
    clearPreviewSvgHoverState: previewShellRuntime.clearPreviewSvgHoverState,
    collectPreviewSnapTargets: previewShellRuntime.collectPreviewSnapTargets,
    collectPreviewMultiResizeSelection: previewShellRuntime.collectPreviewMultiResizeSelection,
    collectPreviewSelectionActionInfo: previewShellRuntime.collectPreviewSelectionActionInfo,
    commitPreviewWaypointInsert: previewShellRuntime.commitPreviewWaypointInsert,
    commitPreviewWaypointRemoval: previewShellRuntime.commitPreviewWaypointRemoval,
    collectPreviewRecursiveRelayoutEntries: previewShellRuntime.collectPreviewRecursiveRelayoutEntries,
    createPreviewResizeStartState: previewShellRuntime.createPreviewResizeStartState,
    dispatchPreviewDragMove: previewShellRuntime.dispatchPreviewDragMove,
    deletePreviewSelectedFramesHost: previewShellRuntime.deletePreviewSelectedFramesHost,
    dispatchPreviewDeleteFramesHost: previewShellRuntime.dispatchPreviewDeleteFramesHost,
    dispatchPreviewDeleteFrames: previewShellRuntime.dispatchPreviewDeleteFrames,
    dispatchPreviewKeyboardShortcut: previewShellRuntime.dispatchPreviewKeyboardShortcut,
    dispatchPreviewDragMoveHost: previewShellRuntime.dispatchPreviewDragMoveHost,
    dispatchPreviewResizeMove: previewShellRuntime.dispatchPreviewResizeMove,
    dispatchPreviewResizeMoveHost: previewShellRuntime.dispatchPreviewResizeMoveHost,
    dispatchPreviewWaypointDragMoveHost: previewShellRuntime.dispatchPreviewWaypointDragMoveHost,
    completePreviewDragInteraction: previewShellRuntime.completePreviewDragInteraction,
    completePreviewResizeInteraction: previewShellRuntime.completePreviewResizeInteraction,
    completePreviewWaypointDragInteraction: previewShellRuntime.completePreviewWaypointDragInteraction,
    createPreviewArrowWaypointRuntime: previewShellRuntime.createPreviewArrowWaypointRuntime,
    createPreviewKeyboardRuntime: previewShellRuntime.createPreviewKeyboardRuntime,
    createPreviewKeyboardRuntimeFromHost:
      previewShellRuntime.createPreviewKeyboardRuntimeFromHost,
    createPreviewPointerInteractionRuntimeFromHost:
      previewShellRuntime.createPreviewPointerInteractionRuntimeFromHost,
    createPreviewPointerInteractionRuntime: previewShellRuntime.createPreviewPointerInteractionRuntime,
    createPreviewResizeInteractionRuntime:
      previewShellRuntime.createPreviewResizeInteractionRuntime,
    createPreviewResizeInteractionRuntimeFromHost:
      previewShellRuntime.createPreviewResizeInteractionRuntimeFromHost,
    createPreviewTextEditRuntime: previewShellRuntime.createPreviewTextEditRuntime,
    createPreviewTextEditRuntimeFromHost:
      previewShellRuntime.createPreviewTextEditRuntimeFromHost,
    createPreviewSelectionChromeRuntimeFromHost:
      previewShellRuntime.createPreviewSelectionChromeRuntimeFromHost,
    createPreviewSelectionChromeRuntime: previewShellRuntime.createPreviewSelectionChromeRuntime,
    createPreviewStageBindingRuntimeFromHost:
      previewShellRuntime.createPreviewStageBindingRuntimeFromHost,
    createPreviewStageBindingRuntime: previewShellRuntime.createPreviewStageBindingRuntime,
    createSelectionTargetOverrideEntries: previewShellRuntime.createSelectionTargetOverrideEntries,
    createPreviewDragStartState: previewShellRuntime.createPreviewDragStartState,
    createPreviewWaypointDragState: previewShellRuntime.createPreviewWaypointDragState,
    findPreviewArrowAtPoint: previewShellRuntime.findPreviewArrowAtPoint,
    findDeepestPreviewComponent: previewShellRuntime.findDeepestPreviewComponent,
    findPreviewComponentAtDepth: previewShellRuntime.findPreviewComponentAtDepth,
    handlePreviewDoubleClickSelectionHost: previewShellRuntime.handlePreviewDoubleClickSelectionHost,
    isAutolayoutParentLayout: previewShellRuntime.isAutolayoutParentLayout,
    normalizeSelectionGap: previewShellRuntime.normalizeSelectionGap,
    readPreviewArrowPointsHost: previewShellRuntime.readPreviewArrowPointsHost,
    renderPreviewArrowWaypointHandles: previewShellRuntime.renderPreviewArrowWaypointHandles,
    renderPreviewWaypointHandlesHost: previewShellRuntime.renderPreviewWaypointHandlesHost,
    renderPreviewReorderIndicator: previewShellRuntime.renderPreviewReorderIndicator,
    removePreviewHandlesHost: previewShellRuntime.removePreviewHandlesHost,
    resolveAutolayoutReorderTarget: previewShellRuntime.resolveAutolayoutReorderTarget,
    resolvePreviewDragSnap: previewShellRuntime.resolvePreviewDragSnap,
    resolveDoubleClickSelection: previewShellRuntime.resolveDoubleClickSelection,
    resolvePointerSelection: previewShellRuntime.resolvePointerSelection,
    renderPreviewTreeSelectionHost: previewShellRuntime.renderPreviewTreeSelectionHost,
    resolvePreviewAutolayoutDragContext: previewShellRuntime.resolvePreviewAutolayoutDragContext,
    resolvePreviewComponentSelectionState: previewShellRuntime.resolvePreviewComponentSelectionState,
    resolvePreviewResizeHandlePlan: previewShellRuntime.resolvePreviewResizeHandlePlan,
    resolvePreviewWaypointDragMove: previewShellRuntime.resolvePreviewWaypointDragMove,
    restorePreviewPropagatedResizeOverrides: previewShellRuntime.restorePreviewPropagatedResizeOverrides,
    resolvePrimarySelectedId: previewShellRuntime.resolvePrimarySelectedId,
    resolveSelectionAlignTargets: previewShellRuntime.resolveSelectionAlignTargets,
    resolveSelectionDistributeTargets: previewShellRuntime.resolveSelectionDistributeTargets,
    resolvePreviewDiagramRootFrameId: previewShellRuntime.resolvePreviewDiagramRootFrameId,
    showPreviewContextMenu: previewShellRuntime.showPreviewContextMenu,
    showPreviewResizeHandlesHost: previewShellRuntime.showPreviewResizeHandlesHost,
    startPreviewPointerInteractionHost: previewShellRuntime.startPreviewPointerInteractionHost,
    startPreviewResizeHost: previewShellRuntime.startPreviewResizeHost,
    startPreviewWaypointDragHost: previewShellRuntime.startPreviewWaypointDragHost,
    syncPreviewSelectionUi: previewShellRuntime.syncPreviewSelectionUi,
    syncPreviewSvgHoverState: previewShellRuntime.syncPreviewSvgHoverState,
    updatePreviewArrowVisualHost: previewShellRuntime.updatePreviewArrowVisualHost,
    rebuildPreviewArrowSvgHost: previewShellRuntime.rebuildPreviewArrowSvgHost,
  }),
  scene: Object.freeze({
    applyPreviewWaypointOverridesHost: previewShellRuntime.applyPreviewWaypointOverridesHost,
    bindPreviewGridControls: previewShellRuntime.bindPreviewGridControls,
    createPreviewEditorSceneFacadeFromEditorHost:
      previewShellRuntime.createPreviewEditorSceneFacadeFromEditorHost,
    createPreviewEditorSceneFacadeFromRuntime:
      previewShellRuntime.createPreviewEditorSceneFacadeFromRuntime,
    createPreviewGridRuntimeFromEditorHost:
      previewShellRuntime.createPreviewGridRuntimeFromEditorHost,
    createPreviewGridRuntimeHost: previewShellRuntime.createPreviewGridRuntimeHost,
    cyclePreviewGuideModeHost: previewShellRuntime.cyclePreviewGuideModeHost,
    createPreviewGridOverlayScene: previewShellRuntime.createPreviewGridOverlayScene,
    dispatchPreviewGridControlChangeHost: previewShellRuntime.dispatchPreviewGridControlChangeHost,
    populatePreviewGridControls: previewShellRuntime.populatePreviewGridControls,
    populatePreviewGridControlsHost: previewShellRuntime.populatePreviewGridControlsHost,
    readPreviewGridControlStateFromDom: previewShellRuntime.readPreviewGridControlStateFromDom,
    dispatchPreviewGridControlChange: previewShellRuntime.dispatchPreviewGridControlChange,
    readPreviewStageCanvasDimensions: previewShellRuntime.readPreviewStageCanvasDimensions,
    refreshPreviewGridInfoFromLayoutHost: previewShellRuntime.refreshPreviewGridInfoFromLayoutHost,
    refreshPreviewSceneHost: previewShellRuntime.refreshPreviewSceneHost,
    refreshPreviewTreeOverrideStateHost: previewShellRuntime.refreshPreviewTreeOverrideStateHost,
    rerenderPreviewStageFromModelHost: previewShellRuntime.rerenderPreviewStageFromModelHost,
    rerenderPreviewStageHost: previewShellRuntime.rerenderPreviewStageHost,
    renderPreviewGridOverlayHost: previewShellRuntime.renderPreviewGridOverlayHost,
    resolvePreviewGridControlRuntimeUpdateHost: previewShellRuntime.resolvePreviewGridControlRuntimeUpdateHost,
    resolvePreviewGridControlRuntimeUpdate: previewShellRuntime.resolvePreviewGridControlRuntimeUpdate,
    resolvePreviewGridInfo: previewShellRuntime.resolvePreviewGridInfo,
    resolvePreviewGridInfoFromRuntimeState: previewShellRuntime.resolvePreviewGridInfoFromRuntimeState,
    renderPreviewTreePanel: previewShellRuntime.renderPreviewTreePanel,
    syncPreviewTreeOverrideState: previewShellRuntime.syncPreviewTreeOverrideState,
    syncPreviewTreeSelectionState: previewShellRuntime.syncPreviewTreeSelectionState,
    runPreviewConstraintValidationHost: previewShellRuntime.runPreviewConstraintValidationHost,
    syncPreviewConstraintStatus: previewShellRuntime.syncPreviewConstraintStatus,
    updatePreviewConstraintStatusHost: previewShellRuntime.updatePreviewConstraintStatusHost,
    updatePreviewOverrideSummaryHost: previewShellRuntime.updatePreviewOverrideSummaryHost,
    formatPreviewOverrideSummary: previewShellRuntime.formatPreviewOverrideSummary,
  }),
});
