export {
  type Line,
  createLine,
  Fill,
  Border,
  Direction,
  Sizing,
  Align,
  Justify,
  type Arrow,
  createArrow,
  type LayoutState,
  type FrameInit,
  Frame,
  type PositionType,
  type FrameDiagramInit,
  FrameDiagram,
  type CoercedOverride,
  enforceFillHugInvariant,
} from './frame-model.js';

export {
  BASELINE_UNIT,
  DEFAULT_MAX_WIDTH_CHARS,
  NO_WRAP_MAX_WIDTH_CHARS,
  BLOCK_WIDTH,
  BOX_MIN_HEIGHT,
  INSET,
  DEFAULT_FRAME_STROKE_WIDTH,
  ICON_SIZE,
  BODY_LINE_STEP,
  BODY_SIZE,
  LINE_HEIGHTS_BY_SIZE,
  defaultLineStep,
  roundUpToGrid,
  sizeToPx,
  steppedLinesHeight,
  clampToConstraints,
  setActiveGridStep,
  getActiveGridStep,
} from './tokens.js';

export {
  type LineSpec,
  type TextMeasureRequest,
  type TextMeasureAdapter,
  estimateLineWidth,
  letterSpacingPx,
  letterSpacingAdvance,
  lineSpecToMeasureRequest,
  wrapTextLines,
  lineToSpec,
  linesToSpecs,
  MockTextAdapter,
} from './text-measure.js';

export {
  CanvasTextAdapter,
  type CanvasTextAdapterOptions,
} from './canvas-text-adapter.js';

export {
  distributeFillSpace,
  alignOffset,
  measure,
  remeasureWithWidthConstraints,
  place,
  layoutFrameTree,
  type LayoutOutput,
  type LayoutOptions,
} from './layout.js';

export {
  computeLevel,
  resolveStyles,
} from './resolve-styles.js';

export {
  frameHasTextContent,
  applyTextLayoutDefaults,
  hasCharWrapCap,
  maxWidthPxFromChars,
  resolveLeafTextWrapWidth,
} from './text-layout.js';

export {
  layoutElkFrameDiagram,
  type ElkLayoutOptions,
} from './elk-layout.js';

export {
  ELK_LAYERED_PARAM_SPECS,
  elkParamGroups,
  resolvedElkOptionsForFamily,
  layeredConfigForFamily,
} from '@diagram-generator/graph-layout-elk';

export { applyHeadingAsChild } from './heading-synthesis.js';

export {
  FRAME_CLASS_DEFS,
  applyFrameClass,
  strokeWidthForClass,
  effectiveResolvedStrokeWidth,
  type FrameClassDefinition,
  type FrameTextStyle,
} from './frame-classes.js';

export {
  annotationTextToSpec,
  frameOwnedHeadingToSpec,
  frameOwnedLabelToSpec,
  frameOwnedTextBlocks,
  frameOwnedTextBlockRole,
  frameOwnedTextBlockGap,
  resolvedSpecTypography,
  usesHeadingStyleSnapshot,
  type ResolvedSpecTypography,
} from './resolved-spec-typography.js';

export {
  applyForceNodePatch,
  createInitialForceSnapshot,
  exportForceAuthoredSpec,
  exportForceSnapshot,
  tickForceSimulation,
  updateForceSimulationParams,
  type ForceAuthoredSpec,
  type ForceLinkSpec,
  type ForceNodePatch,
  type ForceNodeSpec,
  type ForceRenderSpec,
  type ForceSimulationConfig,
  type ForceRuntimeLink,
  type ForceRuntimeNode,
  type ForceRuntimeSnapshot,
  type ForceSimulationSpec,
} from './force-runtime.js';

export {
  layoutSequenceDiagram,
  type SequenceLayoutConfig,
  type SequenceLayoutGroupSpan,
  type SequenceLayoutMessageRow,
  type SequenceLayoutNoteBox,
  type SequenceLayoutParticipantBox,
  type SequenceLayoutResult,
} from './sequence-layout/layout.js';

export { renderSequenceDiagramToSvg } from './sequence-layout/render-svg.js';
export type { SequenceSvgRenderOptions } from './sequence-layout/render-svg.js';

export {
  routeArrows,
} from './arrow-routing.js';
export type { RoutedArrow } from './arrow-routing.js';

export {
  normalizeSequenceDiagram,
  type NormalizeSequenceDiagramResult,
  type SequenceDiagramInput,
  type SequenceDiagramSpec,
  type SequenceGroup,
  type SequenceGroupInput,
  type SequenceLine,
  type SequenceMessage,
  type SequenceMessageInput,
  type SequenceModelDiagnostic,
  type SequenceNote,
  type SequenceNoteInput,
  type SequenceNotePlacement,
  type SequenceParticipant,
  type SequenceParticipantInput,
  type SequenceParticipantKind,
} from './sequence-layout/model.js';

export {
  applyPreviewSvgOverrides,
  captureEditorSnapshot,
  cloneEditorSnapshotValue,
  normalizeGridOverrides,
  parseEditorSnapshot,
  serializeEditorSnapshot,
  createPreviewLoadFailureMarkup,
  createPreviewLoadLoadingMarkup,
  createPreviewLoadUnavailableMarkup,
  loadPreviewSvg,
  normalizePreviewLoadInvocation,
  resolvePreviewFrameTreeSeed,
  bindPreviewShellResize,
  EditorUndoStack,
  clampPreviewShellWidth,
  clearPreviewShellWidth,
  createOverridePatchCommand,
  createPreviewOverrideExportText,
  createPreviewMissingInspectorMarkup,
  createStatePatchCommand,
  overridePatchChanged,
  EditorStateStore,
  captureOverrideEntries,
  createEditorStateStore,
  PERSIST_FRAME_KEYS,
  UNSUPPORTED_PERSIST_FRAME_KEYS,
  PERSIST_INT_FRAME_KEYS,
  PERSIST_LOWER_FRAME_KEYS,
  RELAYOUT_FRAME_KEYS,
  UNDO_RELAYOUT_FRAME_KEYS,
  hasV3FrameOverride,
  filterRelayoutOverrideEntry,
  createSelectionActionInfo,
  createMultiSelectionInspectorViewModel,
  createMultiSelectionAlignState,
  createMultiSelectionContainerState,
  createMultiSelectionSizingState,
  resolveMultiSelectionInspectorState,
  createSingleSelectionAutolayoutState,
  createSingleSelectionInspectorViewModel,
  hasPreviewNodeTextContent,
  applySelectionStateMutation,
  applyReorderOrder,
  clampSelectionTarget,
  dispatchPreviewDragCompletion,
  dispatchPreviewDragMove,
  dispatchPreviewResizeMove,
  dispatchPreviewResizeCompletion,
  resolveDragCompletion,
  resolveResizeCompletion,
  collectRecursiveRelayoutEntries,
  createMultiSelectionResizeOverrides,
  createNudgeOverrideEntries,
  collectPreviewSelectionActionInfo,
  createSelectionTargetOverrideEntries,
  dispatchPreviewKeyboardShortcut,
  findDeepestPreviewComponent,
  findPreviewComponentAtDepth,
  flattenPreviewTreeEntries,
  formatPreviewOverrideSummary,
  initPreviewShellResizeBindings,
  initPreviewOverrideToolbar,
  bindPreviewStageSvgInteraction,
  clearPreviewSvgHoverState,
  clearPreviewCoercedOverrides,
  clearPreviewReorderIndicator,
  collectPreviewCoercedKeys,
  collectPreviewMultiResizeSelection,
  createOriginalOverrideEntries,
  createPreviewDragStartState,
  createResizePersistencePlan,
  ensurePreviewSvgHitAreas,
  isAutolayoutParentLayout,
  colSpanToPx,
  createPreviewGridOverrides,
  createPreviewGridOverlayScene,
  PREVIEW_STYLE_SEMANTICS,
  applyPreviewStyleFields,
  applyVisiblePreviewStyleOverride,
  applyMultiFramePropMutation,
  applyMultiFrameSizeMutation,
  applySingleFramePropMutation,
  applySingleFrameSizeMutation,
  bindPreviewArrowSegmentInsertHandles,
  createPreviewWaypointDragState,
  connectPreviewSse,
  createPreviewSaveClientInitConfig,
  insertPreviewWaypoint,
  readPreviewArrowEndpoints,
  rebuildPreviewArrowSvg,
  collectPreviewTextEditingGroups,
  ensurePreviewEditorState,
  ensurePreviewElkPreviewController,
  extractPreviewDiagramOptionEntries,
  findPreviewEditableTextTarget,
  findPreviewTextBlockAtPoint,
  hasPreviewVisibleStylePicker,
  initPreviewDiagramNavigation,
  initPreviewSaveClient,
  initPreviewShellCoordinator,
  initPreviewViewModes,
  inferSelectionGap,
  inferPreviewStyleFromFields,
  inferPreviewStyleFromNode,
  isPreviewStructuralWrapper,
  isPreviewStyleableComponentType,
  isNudgeKey,
  isGridControlInputId,
  mergeRelativeOverrideEntries,
  normalizePreviewInspectorWidthUnit,
  normalizePreviewStyleFill,
  normalizePreviewStyleName,
  normalizePreviewStyleStrokeOrBorder,
  normalizePreviewDiagramPath,
  pxToColSpan,
  pxToRowSpan,
  previewTreeHasFrameId,
  readPreviewRenderedComponentBounds,
  resizeBoundsFromHandle,
  resolveBasePreviewStyleName,
  renderPreviewSingleSelectionInspector,
  resolvePreviewConstraintStatus,
  resolveEffectivePreviewStyleName,
  resolveMultiSelectionPreviewStyleState,
  resolveKeyboardShortcutAction,
  resolveSelectionAlignTargets,
  resolveSelectionDistributeTargets,
  resolvePreviewGridControlDomPatch,
  resolvePreviewGridControlState,
  resolvePreviewGridControlInputState,
  resolvePreviewGridControlRuntimeUpdate,
  resolvePreviewGridControlStateFromDomState,
  resolvePreviewGridInfo,
  resolvePreviewGridInfoFromControlState,
  resolvePreviewGridInfoFromRuntimeState,
  resolvePreviewGridMarginsFromInputState,
  resolveSingleResizeOverride,
  resolveDoubleClickSelection,
  resolveAutolayoutReorderTarget,
  resolvePointerSelection,
  resolvePreviewTextBlockRole,
  resolvePreviewTextEditCommit,
  resolvePreviewTextEditStartState,
  resolvePreviewTextEditorBlockStyle,
  resolvePreviewTextEditorSurface,
  resolvePrimarySelectedId,
  resolvePreviewResizeHandlePlan,
  resolvePreviewAutolayoutDragContext,
  normalizePreviewSplitDirection,
  normalizePreviewViewMode,
  normalizeSelectionGap,
  previewShellWidthToRem,
  readPreviewShellWidth,
  removePreviewWaypoint,
  renderMultiSelectionInspectorPanel,
  renderPreviewArrowWaypointHandles,
  resolvePreviewArrowSvgUpdatePlan,
  resolvePreviewWaypointDragMove,
  resolvePreviewArrowWaypointHandlePositions,
  resolvePreviewArrowhead,
  renderPreviewTextLines,
  resolveSteppedPreviewDiagramUrl,
  resolvePreviewEditableComponentId,
  resolvePreviewRuntimeSizingValue,
  resolvePreviewShellCssLengthPx,
  resolvePreviewArrowShiftedSegments,
  resolvePreviewArrowSideShift,
  resolvePreviewOverridePatchRestorePlan,
  resolvePreviewSerializedStateRestorePlan,
  resolveSingleSelectionAutolayoutPanelOptions,
  resolveSingleSelectionInspectorPanelRenderOptions,
  resolveSingleSelectionPreviewStyleState,
  resolvePreviewReflowShiftMap,
  renderSingleSelectionAutolayoutPanel,
  renderSingleSelectionInspectorPanel,
  resolvePreviewFrameSizePx,
  restorePreviewOverrideEntries,
  restorePreviewOverridePatch,
  restorePreviewSerializedState,
  rowSpanToPx,
  renderPreviewReorderIndicator,
  renderPreviewTreePanel,
  prunePreviewCollinearWaypoints,
  runPreviewRelayout,
  snapshotNeedsPreviewRelayout,
  registerPreviewPageshowReload,
  showPreviewContextMenu,
  syncPreviewBrowseLinksToPath,
  syncPreviewDiagramPickerToPath,
  syncPreviewConstraintStatus,
  syncPreviewSvgHoverState,
  syncPreviewTreeOverrideState,
  syncPreviewTreeSelectionState,
  teardownPreviewStageSvgInteraction,
  createPreviewResizeStartState,
  shiftPreviewArrowheadPoints,
  applyPreviewReferenceImageState,
  applyPreviewSplitDirectionState,
  applyPreviewViewModeState,
  updatePreviewArrowSvg,
  writePreviewShellWidth,
} from './preview-shell/index.js';
export type {
  ApplyPreviewSvgOverridesOptions,
  PreviewArrowDelta,
  PreviewBuildStatusUpdate,
  ConnectPreviewSseOptions,
  PreviewDiagramNavigationInitOptions,
  PreviewDiagramOptionEntry,
  EditorSnapshot,
  EditorSnapshotInput,
  EditorOverridePatchCommand,
  EditorStatePatchCommand,
  EditorUndoCommand,
  EditorUndoStackOptions,
  PendingUndoableAction,
  EditorStateStoreDeps,
  EditorStateStoreOptions,
  InitPreviewOverrideToolbarOptions,
  PersistFrameKey,
  PreviewRelayoutOverrideEntry,
  PreviewRelayoutResult,
  PreviewRelayoutStatus,
  RelayoutFrameKey,
  InspectorSelectionItem,
  InspectorSelectionParentLayout,
  MultiSelectionInspectorViewModel,
  MultiSelectionAlignItem,
  MultiSelectionAlignState,
  MultiSelectionContainerItem,
  MultiSelectionContainerState,
  MultiSelectionInspectorResolvedState,
  MultiSelectionInspectorRuntimeItem,
  MultiSelectionInspectorPanelRenderOptions,
  MultiSelectionSizingItem,
  MultiSelectionSizingState,
  MultiSelectionStyleState,
  SelectionActionPlanItem,
  SelectionAlignMode,
  CollectPreviewSelectionActionInfoOptions,
  DoubleClickSelectionResolution,
  DragCompletionPlan,
  DragReorderTarget,
  PreviewAutolayoutDragContext,
  PreviewDragDelta,
  PreviewDragCompletionDispatchOptions,
  PreviewDragCompletionState,
  PreviewDragMoveDispatchOptions,
  PreviewDragMoveResult,
  PreviewDragMoveState,
  PreviewDragSnapResult,
  PreviewDragSnapTargets,
  PreviewHitNodeBounds,
  PreviewHitTestNode,
  PreviewHitTestOptions,
  InspectorDeltaState,
  InspectorDirection,
  InspectorEffectiveDeltaState,
  InspectorPositionType,
  InspectorSizingMode,
  PreviewAutolayoutInspectorNode,
  PreviewAutolayoutInspectorNodeData,
  SingleSelectionAutolayoutPanelRenderOptions,
  PreviewSizingAxis,
  PreviewArrowEndpointShift,
  PreviewArrowEndpoints,
  PreviewArrowPoint,
  PreviewArrowSegmentCoordinate,
  PreviewArrowSvgUpdatePlan,
  PreviewWaypointDragAxis,
  PreviewWaypointDragMoveResolution,
  PreviewWaypointDragState,
  PreviewArrowhead,
  PreviewEditorStateApi,
  PreviewEditorStateInitOptions,
  PreviewElkControllerApi,
  PreviewElkControllerInitOptions,
  PreviewEventSourceLike,
  PreviewPageshowReloadOptions,
  PreviewSaveClientApi,
  PreviewSaveClientInitConfig,
  PreviewSaveClientInitOptions,
  PreviewShellCoordinatorInitOptions,
  PreviewTextEditCommitResolution,
  PreviewTextEditStartState,
  PreviewTextEditorBlockStyle,
  PreviewTextEditorRole,
  PointerSelectionResolution,
  InteractionDeltaPatch,
  InteractionDeltaValue,
  InteractionOverrideEntry,
  KeyboardShortcutAction,
  LoadPreviewSvgOptions,
  MultiSelectionResizeMember,
  MultiSelectionResizeOverride,
  PreviewFallbackResponse,
  NudgeKey,
  NudgeSelectionItem,
  PreviewKeyboardDelta,
  PreviewKeyboardDispatchOptions,
  PreviewFrameTreeSeed,
  PreviewGridControlState,
  PreviewGridControlInputState,
  PreviewFrameMutationNode,
  PreviewFrameMutationNodeData,
  PreviewConstraintStatus,
  PreviewConstraintSummary,
  PreviewInspectorArrowNode,
  PreviewInspectorGridInfo,
  PreviewFrameOverrideEntry,
  PreviewFrameOverrideMap,
  PreviewFramePropMutationKind,
  PreviewFramePropMutationResult,
  PreviewFrameSizeDimension,
  PreviewOverrideExportEntry,
  PreviewOverrideBoxStylePreset,
  PreviewOverrideDelta,
  PreviewOverrideEntry,
  PreviewOverridePatchRestorePlan,
  PreviewOverrideRelayoutStatus,
  PreviewOverrideRootNode,
  PreviewOverrideTreeNode,
  PreviewRestoreNode,
  PreviewRenderedStyleFields,
  PreviewGridInfoState,
  PreviewGridInfo,
  PreviewGridOverlayLine,
  PreviewGridOverlayRect,
  PreviewGridOverlayScene,
  PreviewGridOverlayShape,
  PreviewLoadCanonicalState,
  PreviewLoadExecutionMode,
  PreviewLoadInvocationOptions,
  PreviewLoadNormalizedOptions,
  PreviewLoadRenderResult,
  PreviewLocalRelayoutStatus,
  PreviewStyleMode,
  PreviewStyleNode,
  PreviewStyleNodeData,
  PreviewStyleOverrideEntry,
  PreviewStyleOverrideMap,
  PreviewShellTreeEntry,
  PreviewShellTreeNode,
  PreviewSingleSelectionInspectorNode,
  PreviewStageInteractionHandlers,
  RunPreviewRelayoutOptions,
  ReorderResolution,
  ReorderTargetPoint,
  RenderPreviewSingleSelectionInspectorOptions,
  RenderPreviewTreePanelOptions,
  ResolvePreviewGridInfoParams,
  ResizePersistenceEntry,
  ResizePersistenceItem,
  ResizePersistencePlan,
  ResizeCompletionPlan,
  PreviewResizeCompletionDispatchOptions,
  PreviewResizeCompletionState,
  PreviewResizeMoveDispatchOptions,
  PreviewResizeMoveResult,
  PreviewResizeMoveState,
  PreviewResizeNodeBounds,
  PreviewResizeSelection,
  BindPreviewStageSvgInteractionOptions,
  ResizeBounds,
  ResizeBoundsInput,
  ResizeGuideLine,
  RestorePreviewOverridePatchOptions,
  RestorePreviewSerializedStateOptions,
  SingleResizeOverride,
  SingleResizeOverrideInput,
  SelectionActionInfo,
  SelectionDistributeAxis,
  SelectionParentBounds,
  PreviewSelectionActionInfo,
  PreviewSelectionActionItem,
  PreviewSelectionActionNode,
  PreviewSelectionActionNodeData,
  PreviewSelectionDelta,
  ShowPreviewContextMenuAction,
  ShowPreviewContextMenuOptions,
  SelectionStateMutation,
  SelectionStateSnapshot,
  SelectionTargetOverrideEntry,
  SelectionTargetPoint,
  PreviewSplitDirection,
  PreviewViewMode,
  PreviewViewModesInitOptions,
  SingleSelectionAutolayoutState,
  SingleSelectionInspectorViewModel,
  SingleSelectionInspectorPanelRenderOptions,
  SingleSelectionInspectorViolation,
  SingleSelectionPreviewStyleState,
  MultiSelectionPreviewStyleItem,
  MultiSelectionPreviewStyleState,
  PreviewSerializedStateRestorePlan,
} from './preview-shell/index.js';

export {
  serializeFrameDiagram,
  serializeFrame,
  deserializeFrameWire,
  deserializeFrameDiagramWire,
} from './frame-serialize.js';

export {
  ELK_LAYERED_PREVIEW_ENGINE,
  FORCE_PREVIEW_ENGINE,
  FORCE_PREVIEW_PARAM_SPECS,
  SEQUENCE_PREVIEW_ENGINE,
  PREVIEW_ENGINE_REGISTRY,
  elkLayeredPreviewControlSpecs,
  getPreviewEngine,
  listPreviewEngines,
  resolvePreviewEngine,
  serializePreviewEngineManifest,
} from './preview-engine/index.js';
export type {
  PreviewControlKind,
  PreviewControlSpec,
  PreviewEngineApiRoutes,
  PreviewEngineCapabilities,
  PreviewEngineContext,
  PreviewEngineManifest,
  PreviewShellMode,
} from './preview-engine/index.js';
