export {
  type Line,
  createLine,
  Fill,
  Border,
  Direction,
  type FlowDirection,
  Sizing,
  Align,
  Justify,
  type Arrow,
  createArrow,
  type DiagramOverlay,
  type LayoutState,
  type FrameInit,
  Frame,
  type PositionType,
  type FrameDiagramInit,
  FrameDiagram,
  type CoercedOverride,
  enforceFillHugInvariant,
} from './frame-model.js';

export {
  BASELINE_UNIT,
  DEFAULT_MAX_WIDTH_CHARS,
  NO_WRAP_MAX_WIDTH_CHARS,
  BLOCK_WIDTH,
  BOX_MIN_HEIGHT,
  INSET,
  GRID_GUTTER,
  DEFAULT_FRAME_STROKE_WIDTH,
  ICON_SIZE,
  BODY_LINE_STEP,
  BODY_SIZE,
  ARROW_HEAD_LENGTH,
  ARROW_HEAD_HALF_WIDTH,
  ARROW_COLOR,
  LINE_HEIGHTS_BY_SIZE,
  defaultLineStep,
  roundUpToGrid,
  sizeToPx,
  steppedLinesHeight,
  clampToConstraints,
  setActiveGridStep,
  getActiveGridStep,
} from './tokens.js';

export {
  SHARED_BOX_RHYTHM,
  estimateSharedBoxTextHeight,
  estimateSharedBoxTextWidth,
  type SharedBoxRhythm,
} from './shared-box-rhythm.js';

export {
  type LineSpec,
  type TextMeasureRequest,
  type TextMeasureAdapter,
  estimateLineWidth,
  letterSpacingPx,
  letterSpacingAdvance,
  lineSpecToMeasureRequest,
  wrapTextLines,
  lineToSpec,
  linesToSpecs,
  MockTextAdapter,
} from './text-measure.js';

export {
  CanvasTextAdapter,
  type CanvasTextAdapterOptions,
} from './canvas-text-adapter.js';

export {
  HarfBuzzTextAdapter,
  createHarfBuzzTextAdapter,
  createDefaultHarfBuzzTextAdapter,
  type HarfBuzzTextAdapterOptions,
  type HarfBuzzTextAdapterFetchOptions,
} from './harfbuzz-text-adapter.js';
export {
  isTextShapeCompatibleAdapter,
  shapeLineSpec,
  type ShapeTextRunRequest,
  type TextShapeCompatibleAdapter,
} from './text-adapter/shape-compatible.js';

export {
  distributeFillSpace,
  alignOffset,
  measure,
  remeasureWithWidthConstraints,
  place,
  layoutFrameTree,
  type LayoutOutput,
  type LayoutOptions,
} from './layout.js';

export {
  computeLevel,
  resolveStyles,
} from './resolve-styles.js';

export {
  annotationTextToSpec,
  frameOwnedHeadingToSpec,
  frameOwnedLabelToSpec,
  frameOwnedTextBlocks,
  frameOwnedTextBlockRole,
  frameOwnedTextBlockGap,
  resolvedSpecTypography,
} from './resolved-spec-typography.js';

export {
  frameHasTextContent,
  applyTextLayoutDefaults,
  hasCharWrapCap,
  maxWidthPxFromChars,
  resolveLeafTextWrapWidth,
} from './text-layout.js';

export {
  applyHeadingAsChild,
  findSyntheticBody,
  findSyntheticHeading,
  isSyntheticBodyFrame,
  isSyntheticHeadingFrame,
} from './heading-synthesis.js';
export { loadFrameYaml } from './frame-yaml-loader.js';
export { serializeFrameDiagram, serializeFrame, deserializeFrameWire, deserializeFrameDiagramWire } from './frame-serialize.js';
export { buildGridInfo, type GridInfo } from './grid-info.js';
export { buildComponentTree, type ComponentInfo } from './component-tree.js';
export { renderFrameDiagramToSvg, type SvgRenderOptions } from './svg-render.js';
export {
  exportFrameDiagramToDrawio,
  type DrawioExportOptions,
  type DrawioExportResult,
} from './drawio-render.js';
export { layoutFrameDiagramForExport } from './frame-diagram-export-layout.js';
export {
  emitFrameDiagramDisplayList,
} from './render-adapter/display-list.js';
export { renderDisplayListToSvg } from './render-adapter/svg.js';
export {
  renderDisplayListToDrawio,
  type DrawioRenderOptions,
  type DrawioRenderResult,
} from './render-adapter/drawio.js';
export type {
  AssetRef,
  Color,
  DisplayList,
  DisplayListItem,
  GlyphRunItem,
  GroupItem,
  LineItem,
  Paint,
  PathCommand,
  PathItem,
  RectItem,
  ShapedGlyph,
  ShapedRun,
  StrokeStyle,
  SvgFragmentItem,
  Viewport,
} from './render-ir.js';
export {
  collectIconNames,
  createFsIconLoader,
  extractSvgInnerMarkup,
  preloadIconMarkup,
  safeIconFileName,
  tintIconInnerMarkup,
  type IconInnerMarkupLoader,
} from './icon-embed.js';

export {
  FRAME_CLASS_DEFS,
  applyFrameClass,
  strokeWidthForClass,
  effectiveResolvedStrokeWidth,
  type FrameClassDefinition,
  type FrameTextStyle,
} from './frame-classes.js';

export {
  maxStructuralChildNestingDepth,
  structuralLevelForMaxChildNestingDepth,
  type PromotedStructuralLevel,
  type PromotionNode,
} from './level-promotion.js';

export {
  validateFrameLevelPromotion,
  type LevelPromotionViolation,
} from './level-promotion-frame.js';

export {
  applyForceNodePatch,
  createInitialForceSnapshot,
  exportForceAuthoredSpec,
  exportForceSnapshot,
  tickForceSimulation,
  updateForceSimulationParams,
  type ForceAuthoredSpec,
  type ForceLinkSpec,
  type ForceNodePatch,
  type ForceNodeSpec,
  type ForceRenderSpec,
  type ForceSimulationConfig,
  type ForceRuntimeLink,
  type ForceRuntimeNode,
  type ForceRuntimeSnapshot,
  type ForceSimulationSpec,
} from './force-runtime.js';

export {
  layoutSequenceDiagram,
  type SequenceLayoutConfig,
  type SequenceLayoutGroupSpan,
  type SequenceLayoutMessageRow,
  type SequenceLayoutNoteBox,
  type SequenceLayoutParticipantBox,
  type SequenceLayoutResult,
} from './sequence-layout/layout.js';

export { renderSequenceDiagramToSvg } from './sequence-layout/render-svg.js';
export type { SequenceSvgRenderOptions } from './sequence-layout/render-svg.js';

export {
  ELK_FORCE_PARAM_SPECS,
  ELK_MRTREE_PARAM_SPECS,
  ELK_RADIAL_PARAM_SPECS,
  ELK_RECTPACKING_PARAM_SPECS,
  ELK_STRESS_PARAM_SPECS,
  ELK_LAYERED_PARAM_SPECS,
  elkParamGroups,
  resolvedElkOptionsForFamily,
  layeredConfigForFamily,
} from '@diagram-generator/graph-layout-elk';

export {
  normalizeSequenceDiagram,
  type NormalizeSequenceDiagramResult,
  type SequenceDiagramInput,
  type SequenceDiagramSpec,
  type SequenceGroup,
  type SequenceGroupInput,
  type SequenceLine,
  type SequenceMessage,
  type SequenceMessageInput,
  type SequenceModelDiagnostic,
  type SequenceNote,
  type SequenceNoteInput,
  type SequenceNotePlacement,
  type SequenceParticipant,
  type SequenceParticipantInput,
  type SequenceParticipantKind,
} from './sequence-layout/model.js';

export { compileDiagramYaml } from './diagram-author/compile.js';
export { exportMermaid } from './diagram-author/export-mermaid.js';
export type { MermaidExportResult } from './diagram-author/export-mermaid.js';
export { exportD2 } from './diagram-author/export-d2.js';
export type { D2ExportResult } from './diagram-author/export-d2.js';
export { importD2 } from './diagram-author/import-d2.js';
export type { D2ImportOptions } from './diagram-author/import-d2.js';
export { importMermaid } from './diagram-author/import-mermaid.js';
export type { MermaidImportOptions } from './diagram-author/import-mermaid.js';
export { serializeDiagramYaml } from './diagram-author/serialize-yaml.js';
export type { DiagramImportResult } from './diagram-author/import-result.js';
export type {
  AuthorArrow,
  AuthorFrameNode,
  CompileOptions,
  CompileResult,
  DiagramDocument,
  Diagnostic,
  DiagnosticLevel,
  Edge,
  FrameIndexEntry,
  FrameTemplate,
  LineSpec as AuthorLineSpec,
} from './diagram-author/types.js';

export {
  captureEditorSnapshot,
  cloneEditorSnapshotValue,
  createPreviewEditorBootstrapFacadeFromEditorHost,
  createPreviewEditorBootstrapFacadeFromRuntime,
  createPreviewEditorInteractionFacadeFromBrowserHost,
  createPreviewEditorInteractionFacadeFromEditorHost,
  createPreviewEditorInteractionFacadeFromRuntime,
  createPreviewEditorSceneFacadeFromEditorHost,
  createPreviewEditorSceneFacadeFromRuntime,
  createPreviewEditorRuntimeSetFromEditorHost,
  createPreviewKeyboardRuntime,
  createPreviewKeyboardRuntimeFromHost,
  createPreviewLiveResizeRuntimeFromHost,
  createPreviewLiveResizeRuntime,
  createPreviewPointerInteractionRuntimeFromHost,
  createPreviewPointerInteractionRuntime,
  createPreviewResizeInteractionRuntime,
  createPreviewResizeInteractionRuntimeFromHost,
  createPreviewTextEditRuntime,
  createPreviewTextEditRuntimeFromHost,
  createPreviewGridRuntimeFromEditorHost,
  createPreviewGridRuntimeHost,
  createPreviewSelectionChromeRuntimeFromHost,
  createPreviewSelectionChromeRuntime,
  normalizeGridOverrides,
  parseEditorSnapshot,
  serializeEditorSnapshot,
  createLoadPreviewSvgHostOptionsFromRuntime,
  loadPreviewSvg,
  EditorUndoStack,
  createOverridePatchCommand,
  createStatePatchCommand,
  overridePatchChanged,
  EditorStateStore,
  captureOverrideEntries,
  createEditorStateStore,
  createPreviewEngineWorkspaceState,
  PERSIST_FRAME_KEYS,
  UNSUPPORTED_PERSIST_FRAME_KEYS,
  PERSIST_INT_FRAME_KEYS,
  PERSIST_LOWER_FRAME_KEYS,
  DEFAULT_FRAME_YAML_ENGINE_LAYOUT_NAMESPACE,
  filterSupportedFrameYamlEngineLayoutOverrides,
  getSupportedFrameYamlControlSpecsForNamespace,
  isSupportedFrameYamlEngineLayoutNamespace,
  listFrameYamlEngineLayoutCandidateIds,
  resolveFrameYamlEngineLayoutCandidateId,
  resolveFrameYamlEngineLayoutNamespaceForOverrides,
  activateLayoutOperatorOverrideBucket,
  collectNamespacedLayoutOperatorOverrides,
  layoutOperatorKeyForManifest,
  pruneSessionBucketForManifest,
  readActiveLayoutOperatorOverrideBucket,
  readLayoutOperatorOverrideBucketForManifest,
  readLayoutOperatorOverrideState,
  resolveEffectiveLayoutOperatorOverrides,
  resolveLayoutOperatorOverrideViewModel,
  writeLayoutOperatorOverrideBucketForManifest,
  writeLayoutOperatorOverrideState,
  RELAYOUT_FRAME_KEYS,
  UNDO_RELAYOUT_FRAME_KEYS,
  createPreviewOverridePayload,
  createPreviewSaveClientRuntime,
  createPreviewEditorRelayoutFacadeFromEditorHost,
  createPreviewEditorRelayoutFacadeFromRuntime,
  createPreviewRelayoutRuntimeFromEditorHost,
  resolvePreviewPanelVisibility,
  resolvePreviewVisibleTemplateSections,
  shouldShowPreviewEngineSwitcher,
  reopenPreviewEngineWorkspace,
  persistPreviewEngineWorkspaceActiveEngine,
  setPreviewEngineWorkspaceActiveEngine,
  setPreviewEngineWorkspaceSessionState,
  clearPreviewEngineWorkspaceSessionState,
  hasInvalidPreviewPersistedLayoutEngine,
  previewEngineSupportsSidebarSection,
  PREVIEW_ASIDE_PANEL_GROUPS,
  PREVIEW_PANEL_REGISTRY,
  createPreviewStageBindingRuntimeFromHost,
  createPreviewStageBindingRuntime,
  createPreviewStateRestoreRuntimeFromEditorHost,
  createPreviewStateRestoreRuntime,
  PERSIST_ARROW_KEYS,
  hasPreviewRelayoutFrameOverride,
  hasV3FrameOverride,
  filterRelayoutOverrideEntry,
  RELAYOUT_ARROW_KEYS,
  UNDO_RELAYOUT_ARROW_KEYS,
  resolvePreviewTemplateSectionVisibilityPlaceholders,
} from './preview-shell/index.js';
export type {
  CreatePreviewEditorInteractionFacadeFromEditorHostOptions,
  PreviewEditorInteractionFacade,
  CreatePreviewEditorSceneFacadeFromEditorHostOptions,
  PreviewEditorSceneFacade,
  CreatePreviewEditorRelayoutFacadeFromEditorHostOptions,
  PreviewEditorRelayoutFacade,
  CreatePreviewEditorRuntimeSetFromEditorHostOptions,
  CreatePreviewKeyboardRuntimeFromHostOptions,
  CreatePreviewKeyboardRuntimeOptions,
  CreatePreviewLiveResizeRuntimeFromHostOptions,
  CreatePreviewLiveResizeRuntimeOptions,
  CreatePreviewPointerInteractionRuntimeFromHostOptions,
  CreatePreviewPointerInteractionRuntimeOptions,
  CreatePreviewResizeInteractionRuntimeFromHostOptions,
  CreatePreviewResizeInteractionRuntimeOptions,
  CreatePreviewTextEditRuntimeFromHostOptions,
  CreatePreviewTextEditRuntimeOptions,
  EditorSnapshot,
  EditorSnapshotInput,
  CreatePreviewGridRuntimeHostOptions,
  CreatePreviewSelectionChromeRuntimeFromHostOptions,
  CreatePreviewSelectionChromeRuntimeOptions,
  EditorOverridePatchCommand,
  EditorStatePatchCommand,
  EditorUndoCommand,
  EditorUndoStackOptions,
  PendingUndoableAction,
  PreviewKeyboardRuntime,
  PreviewGridRuntimeEditorHostModel,
  PreviewGridRuntimeEditorStateLike,
  PreviewGridRuntimeHost,
  EditorStateStoreDeps,
  EditorStateStoreOptions,
  CreatePreviewEngineWorkspaceStateOptions,
  CreatePreviewRelayoutRuntimeFromEditorHostOptions,
  PreviewAsidePanelGroup,
  PreviewPanelRegistryEntry,
  PreviewPanelVisibility,
  PreviewSelectionKind,
  PreviewTemplateSectionVisibilityPlaceholder,
  PreviewTemplateSectionKey,
  PreviewUiContext,
  PreviewUiDocumentState,
  PreviewUiSelectionContext,
  PreviewEngineWorkspaceEngine,
  PreviewEngineWorkspaceNavigation,
  PreviewEngineWorkspaceState,
  PreviewEngineWorkspaceTab,
  PersistFrameKey,
  FrameYamlPersistedControlSpec,
  PreviewLiveResizeRuntime,
  PreviewPointerInteractionRuntime,
  PreviewResizeInteractionRuntime,
  PreviewTextEditRuntime,
  PreviewOverrideModelLike,
  PreviewOverrideModelNode,
  PreviewOverridePayload,
  PreviewSaveClientRuntime,
  PreviewSaveClientRuntimeDeps,
  PreviewSaveClientRuntimeOptions,
  CreatePreviewStageBindingRuntimeFromHostOptions,
  PreviewSelectionChromeRuntime,
  CreatePreviewStageBindingRuntimeOptions,
  CreatePreviewStateRestoreRuntimeFromEditorHostOptions,
  CreatePreviewStateRestoreRuntimeOptions,
  PreviewStageBindingRuntime,
  PreviewStateRestoreEditorHostModel,
  PreviewStateRestoreEditorStateLike,
  PreviewStateRestoreRuntime,
  PersistArrowKey,
  RelayoutFrameKey,
} from './preview-shell/index.js';

export {
  PREVIEW_ARROW_COMPONENT_PREFIX,
  collectPreviewArrowComponentEntries,
  createPreviewArrowComponentId,
  isPreviewArrowComponentId,
  parsePreviewArrowComponentId,
  resolvePreviewArrowComponentId,
} from './preview-arrow-component-ids.js';

export {
  AUTOLAYOUT_DOCUMENT_KIND,
  fromFrameDiagram,
  toFrameDiagram,
} from './document-model/schema.js';
export type { AutolayoutDocument } from './document-model/schema.js';

export {
  AUTOLAYOUT_OPERATOR_FACADE,
  evaluateAutolayoutOperator,
} from './operator-autolayout/facade.js';
export type {
  AutolayoutOperatorInputs,
  AutolayoutOperatorOutputs,
  AutolayoutOperatorParams,
  EvaluateContext,
  InputPort,
  OperatorDefinition,
  OutputPort,
  ParameterField,
  ParameterType,
} from './operator-autolayout/facade.js';

export {
  getPreviewDocumentSvgRenderer,
  getPreviewFrameDiagramRenderAdapter,
  createPreviewEngineLayoutControlsRuntime,
  createPreviewEngineShellControllerRuntime,
  FORCE_PREVIEW_SHELL_MODE,
  FRAME_PREVIEW_SHELL_MODE,
  LEGACY_GRID_PREVIEW_SHELL_MODE,
  V3_PREVIEW_ENGINE,
  ELK_LAYERED_PREVIEW_ENGINE,
  ELK_FORCE_PREVIEW_ENGINE,
  ELK_MRTREE_PREVIEW_ENGINE,
  ELK_RADIAL_PREVIEW_ENGINE,
  ELK_RECTPACKING_PREVIEW_ENGINE,
  ELK_STRESS_PREVIEW_ENGINE,
  FORCE_PREVIEW_ENGINE,
  MINDMAP_LITE_PREVIEW_ENGINE,
  BUILTIN_ELK_LAYERED_PREVIEW_ENGINE_INSTALL_UNIT,
  BUILTIN_ELK_FORCE_PREVIEW_ENGINE_INSTALL_UNIT,
  BUILTIN_ELK_MRTREE_PREVIEW_ENGINE_INSTALL_UNIT,
  BUILTIN_ELK_RADIAL_PREVIEW_ENGINE_INSTALL_UNIT,
  BUILTIN_ELK_RECTPACKING_PREVIEW_ENGINE_INSTALL_UNIT,
  BUILTIN_ELK_STRESS_PREVIEW_ENGINE_INSTALL_UNIT,
  BUILTIN_FORCE_PREVIEW_ENGINE_INSTALL_UNIT,
  BUILTIN_SEQUENCE_PREVIEW_ENGINE_INSTALL_UNIT,
  BUILTIN_V3_PREVIEW_ENGINE_INSTALL_UNIT,
  installBuiltinPreviewEngineInstallUnitsRuntime,
  installPreviewEngineInstallUnits,
  installRegisteredPreviewEngineInstallUnits,
  listPreviewEngineInstallUnits,
  registerPreviewEngineInstallUnit,
  installV3PreviewEngine,
  installElkLayeredPreviewEngine,
  installElkForcePreviewEngine,
  installElkMrtreePreviewEngine,
  installElkRadialPreviewEngine,
  installElkRectpackingPreviewEngine,
  installElkStressPreviewEngine,
  installForcePreviewEngine,
  installSequencePreviewEngine,
  installMindmapLitePreviewEngine,
  FORCE_PREVIEW_PARAM_SPECS,
  PREVIEW_ENGINE_REGISTRY,
  isFramePreviewShellMode,
  normalizePreviewShellMode,
  canonicalPreviewLayoutEngineKey,
  canonicalPreviewPersistNamespace,
  registerPreviewEngine,
  registerPreviewDocumentSvgRenderer,
  elkForcePreviewControlSpecs,
  elkLayeredPreviewControlSpecs,
  elkMrtreePreviewControlSpecs,
  elkRadialPreviewControlSpecs,
  elkRectpackingPreviewControlSpecs,
  elkStressPreviewControlSpecs,
  paramSpecToPreviewControl,
  defineGraphLayoutPreviewEngine,
  evaluatePreviewEngineCompatibility,
  getPreviewEngine,
  getPreviewEngineByLayoutKey,
  layoutPreviewFrameDiagramForEngine,
  listCompatiblePreviewEngines,
  listPreviewEnginesBySidebarSection,
  listPreviewEngines,
  renderPreviewDocumentToSvg,
  registerPreviewFrameDiagramRenderAdapter,
  resolvePreviewRenderFamily,
  resolvePreviewEngine,
  serializePreviewEngineManifest,
  summarizeFrameDiagramCompatibility,
  migrateLegacyFrameDiagramEngineState,
  migrateLegacyPreviewEngineNodeBucketsForNamespace,
  migrateLegacyPreviewEngineOverridesForNamespace,
} from './preview-engine/index.js';
export type {
  CompatibilityResult,
  FrameDiagramCompatibilitySummary,
  PreviewEngineInstallUnit,
  PreviewEngineLayoutControlsDocumentLike,
  PreviewEngineLayoutControlsRuntime,
  PreviewEngineLayoutControlsRuntimeInitOptions,
  PreviewEngineLayoutControlsRuntimeOptions,
  PreviewEngineLayoutControlsWindowLike,
  PreviewEngineShellControllerDeps,
  PreviewEngineShellControllerDocumentLike,
  PreviewEngineShellControllerRuntime,
  PreviewEngineShellControllerRuntimeOptions,
  PreviewEngineShellControllerWindowLike,
  PreviewControlKind,
  PreviewControlSpec,
  PreviewDocumentKind,
  PreviewEngineApiRoutes,
  PreviewEngineCapabilities,
  PreviewEngineContext,
  PreviewDocumentSvgRenderResult,
  PreviewDocumentSvgRenderer,
  PreviewEngineHostView,
  MindmapLiteDocumentData,
  MindmapLitePreviewDocument,
  PreviewEngineManifest,
  PreviewPersistNamespace,
  PreviewRenderableDocument,
  PreviewRenderFamily,
  PreviewViewerSidebarSection,
  PreviewShellMode,
  PreviewParamSpec,
  DefinedGraphLayoutPreviewEngine,
  GraphLayoutPreviewEngineDefinition,
} from './preview-engine/index.js';
