import { describe, expect, it } from 'vitest';
import * as browserEntry from '../src/browser-entry.js';
import {
  core,
  previewBridge,
  previewEngines,
  previewShell,
} from '../src/browser-entry.js';
import {
  attemptPreviewDiagramNavigation,
  applyPreviewSelectionStateSnapshot,
  applyPreviewSvgOverrides,
  applyPreviewSvgOverridesHost,
  applyPreviewWaypointOverridesHost,
  applySelectionStateMutation,
  applySingleFramePropMutation,
  applyVisiblePreviewStyleOverride,
  bindPreviewEditorInspectorActionsFromBrowserHost,
  bindPreviewStageSvgInteraction,
  bindPreviewStageSvgInteractionHost,
  bootstrapPreviewEditorHost,
  bootstrapPreviewEditorRuntime,
  captureEditorSnapshot,
  clearPreviewSelectionState,
  cloneEditorSnapshotValue,
  collectPreviewFramesById,
  collectPreviewPlacedBounds,
  collectPreviewRecursiveRelayoutEntries,
  collectPreviewSelectionActionInfo,
  createBootstrapPreviewEditorHostOptionsFromRuntime,
  createBootstrapPreviewEditorRuntimeOptionsFromHost,
  createEditorStateStore,
  createLoadPreviewSvgHostOptionsFromRuntime,
  createLoadPreviewSvgHostOptions,
  createPreviewArrowWaypointRuntime,
  createPreviewBuildStatusUpdater,
  createPreviewDragStartState,
  createPreviewEditorBootstrapFacadeFromEditorHost,
  createPreviewEditorBootstrapFacadeFromRuntime,
  createPreviewEditorInteractionFacadeFromBrowserHost,
  createPreviewEditorInteractionFacadeFromEditorHost,
  createPreviewEditorInteractionFacadeFromRuntime,
  createPreviewEditorRelayoutFacadeFromEditorHost,
  createPreviewEditorRelayoutFacadeFromRuntime,
  createPreviewEditorRuntimeSet,
  createPreviewEditorRuntimeSetFromHost,
  createPreviewEditorRuntimeSetFromRuntime,
  createPreviewEditorSceneFacadeFromEditorHost,
  createPreviewEditorSceneFacadeFromRuntime,
  createPreviewElkViewModeRuntime,
  createPreviewElkViewModeRuntimeFromBrowserHost,
  createPreviewGridEditorBrowserStateFromBrowserHost,
  createPreviewGridEditorInstallOptionsFromLegacyEditorHost,
  createPreviewGridEditorInstallUnitFromBrowserHost,
  createPreviewGridEditorInstallUnitFromEditorHost,
  createPreviewGridEditorInstallUnitFromLegacyEditorHost,
  createPreviewGridEditorRuntimeFromBrowserHost,
  createPreviewGridRuntimeFromEditorHost,
  createPreviewGridRuntimeHost,
  createPreviewInspectorDisplayRuntime,
  createPreviewInspectorMutationRuntime,
  createPreviewInspectorSelectionRuntime,
  createPreviewKeyboardRuntime,
  createPreviewKeyboardRuntimeFromHost,
  createPreviewLayoutBridgeInstallRuntimeFromLegacyBrowserHost,
  createPreviewLiveResizeRuntime,
  createPreviewLiveResizeRuntimeFromHost,
  createPreviewOverrideToolbarHostOptions,
  createPreviewPointerInteractionRuntime,
  createPreviewPointerInteractionRuntimeFromHost,
  createPreviewRelayoutRuntime,
  createPreviewRelayoutRuntimeFromRuntime,
  createPreviewRelayoutRuntimeOptionsFromHost,
  createPreviewRelayoutRuntimeOptionsFromRuntime,
  createPreviewRelayoutRuntimeState,
  createPreviewResizeInteractionRuntime,
  createPreviewResizeInteractionRuntimeFromHost,
  createPreviewResizeStartState,
  createPreviewSaveClientRuntime,
  createPreviewSelectionChromeRuntime,
  createPreviewSelectionChromeRuntimeFromHost,
  createPreviewSelectionRuntime,
  createPreviewStageBindingRuntime,
  createPreviewStageBindingRuntimeFromHost,
  createPreviewStateRestoreRuntime,
  createPreviewStateRestoreRuntimeFromEditorHost,
  cyclePreviewGuideModeHost,
  deletePreviewSelectedFramesHost,
  dispatchPreviewAlignSelectionHost,
  dispatchPreviewApplySelectionTargetsHost,
  dispatchPreviewClearOverride,
  dispatchPreviewDeleteFramesHost,
  dispatchPreviewDistributeSelectionHost,
  dispatchPreviewDragMove,
  dispatchPreviewDragMoveHost,
  dispatchPreviewGridControlChangeHost,
  dispatchPreviewKeyboardShortcut,
  dispatchPreviewMultiFrameAlignHost,
  dispatchPreviewMultiFramePropHost,
  dispatchPreviewMultiFrameSizeHost,
  dispatchPreviewMultiStyleOverrideHost,
  dispatchPreviewRelayoutFailureHost,
  dispatchPreviewRelayoutSuccessHost,
  dispatchPreviewResizeMove,
  dispatchPreviewResizeMoveHost,
  dispatchPreviewSingleFrameAlignHost,
  dispatchPreviewSingleFramePropHost,
  dispatchPreviewSingleFrameSizeHost,
  dispatchPreviewWaypointDragMoveHost,
  ensurePreviewEngineShellCompatController,
  findDeepestPreviewComponent,
  findPreviewArrowAtPoint,
  findPreviewComponentAtDepth,
  fitPreviewSvgToRenderedContent,
  formatPreviewDefinedStyleLabel,
  handlePreviewDoubleClickSelectionHost,
  initPreviewOverrideToolbar,
  initPreviewEditorRuntimeHost,
  installPreviewEditorTestFacadeHost,
  loadPreviewComponentTree,
  loadPreviewGridInfo,
  normalizePreviewStyleName,
  patchPreviewFrameGroup,
  patchPreviewSvgFromLayout,
  populatePreviewGridControls,
  populatePreviewGridControlsHost,
  readPreviewArrowPointsHost,
  readPreviewGridControlStateFromDom,
  rebuildPreviewArrowSvgHost,
  refreshPreviewGridInfoFromLayoutHost,
  refreshPreviewSceneHost,
  registerPreviewEditorDocumentBindingsHost,
  removePreviewHandlesHost,
  renderPreviewBoxStyleOptions,
  renderPreviewEmptyInspectorHost,
  renderFreshPreviewSvg,
  renderPreviewGridOverlayHost,
  renderPreviewFrameTreeToSvg,
  renderPreviewMultiSelectionInspectorHost,
  renderPreviewMultiSelectionInspectorRuntimeHost,
  renderPreviewSelectionInspectorHost,
  renderPreviewSingleSelectionInspectorHost,
  renderPreviewSingleSelectionInspectorRuntimeHost,
  renderPreviewTreeSelectionHost,
  renderPreviewWaypointHandlesHost,
  resolvePreviewComponentSelectionState,
  resolvePreviewEditableComponentId,
  resolvePreviewDiagramRootFrameId,
  resolvePreviewFrameSizePx,
  resolvePreviewGridControlRuntimeUpdate,
  resolvePreviewGridControlRuntimeUpdateHost,
  resolvePreviewLayoutRelayoutStatus,
  resolvePreviewResizeHandlePlan,
  resolvePreviewTextEditStartState,
  resolvePreviewV3RelayoutStatus,
  resolvePrimarySelectedId,
  restorePreviewPropagatedResizeOverrides,
  restorePreviewSelectionIds,
  rerenderPreviewStageFromModelHost,
  rerenderPreviewStageHost,
  schedulePreviewTextEditCommitHost,
  showPreviewResizeHandlesHost,
  startPreviewPointerInteractionHost,
  startPreviewResizeHost,
  startPreviewTextEditHost,
  startPreviewWaypointDragHost,
  suspendPreviewTextEditSelectionChromeHost,
  syncPreviewArrowModelFromFrameTree,
  syncPreviewSelectionUi,
  updatePreviewArrowVisualHost,
  updatePreviewOverrideSummaryHost,
} from '../src/preview-shell/index.js';
import {
  renderPreviewElkDebugOverlay,
  renderPreviewElkRawView,
} from '../src/preview-engine/index.js';
import { routeArrows } from '../src/arrow-routing.js';
import {
  applyForceNodePatch,
  BODY_LINE_STEP,
  BODY_SIZE,
  createLine,
  createPreviewEngineLayoutControlsRuntime,
  createPreviewEngineShellControllerRuntime,
  createPreviewElkLayoutControlsRuntime,
  createPreviewElkShellControllerRuntime,
  ELK_LAYERED_PARAM_SPECS,
  ELK_LAYERED_PREVIEW_ENGINE,
  elkParamGroups,
  FORCE_PREVIEW_PARAM_SPECS,
  getPreviewEngine,
  ICON_SIZE,
  INSET,
  listPreviewEngines,
  resolvePreviewEngine,
  serializePreviewEngineManifest,
} from '../src/index.js';
import { deserializeFrameDiagramWire, deserializeFrameWire } from '../src/frame-serialize.js';
import { effectiveResolvedStrokeWidth } from '../src/frame-classes.js';
import {
  annotationTextToSpec,
  frameOwnedTextBlockGap,
  frameOwnedTextBlockRole,
  frameOwnedTextBlocks,
} from '../src/resolved-spec-typography.js';
import { layoutElkFrameDiagram } from '../src/elk-layout.js';
import { layoutFrameTree } from '../src/layout.js';
import { layoutSequenceDiagram } from '../src/sequence-layout/layout.js';
import { renderSequenceDiagramToSvg } from '../src/sequence-layout/render-svg.js';
import { resolveStyles } from '../src/resolve-styles.js';
import { GRID_GUTTER, sizeToPx } from '../src/tokens.js';
import { wrapTextLines } from '../src/text-measure.js';

const CORE_EXPORT_KEYS = [
  'BODY_LINE_STEP',
  'BODY_SIZE',
  'GRID_GUTTER',
  'ICON_SIZE',
  'INSET',
  'annotationTextToSpec',
  'createLine',
  'deserializeFrameDiagramWire',
  'deserializeFrameWire',
  'effectiveResolvedStrokeWidth',
  'frameOwnedTextBlockGap',
  'frameOwnedTextBlockRole',
  'frameOwnedTextBlocks',
  'layoutElkFrameDiagram',
  'layoutFrameTree',
  'layoutSequenceDiagram',
  'renderSequenceDiagramToSvg',
  'resolveStyles',
  'routeArrows',
  'sizeToPx',
  'wrapTextLines',
] as const;

describe('browser entry contract pilot', () => {
  it('retires flat root-level browser-entry aliases in favor of owner-scoped namespaces', () => {
    expect(Object.keys(browserEntry).sort()).toEqual([
      'core',
      'previewBridge',
      'previewEngines',
      'previewShell',
    ]);
  });

  it('exposes preview-shell bootstrap aliases under a namespaced contract', () => {
    expect(previewShell.bootstrap.attemptPreviewDiagramNavigation).toBe(attemptPreviewDiagramNavigation);
    expect(previewShell.bootstrap.createPreviewEditorBootstrapFacadeFromEditorHost)
      .toBe(createPreviewEditorBootstrapFacadeFromEditorHost);
    expect(previewShell.bootstrap.createPreviewEditorBootstrapFacadeFromRuntime)
      .toBe(createPreviewEditorBootstrapFacadeFromRuntime);
    expect(previewShell.bootstrap.createEditorStateStore).toBe(createEditorStateStore);
    expect(previewShell.bootstrap.cloneEditorSnapshotValue).toBe(cloneEditorSnapshotValue);
    expect(previewShell.bootstrap.captureEditorSnapshot).toBe(captureEditorSnapshot);
    expect(previewShell.bootstrap.createLoadPreviewSvgHostOptionsFromRuntime)
      .toBe(createLoadPreviewSvgHostOptionsFromRuntime);
    expect(previewShell.bootstrap.createLoadPreviewSvgHostOptions).toBe(createLoadPreviewSvgHostOptions);
    expect(previewShell.bootstrap.createBootstrapPreviewEditorHostOptionsFromRuntime)
      .toBe(createBootstrapPreviewEditorHostOptionsFromRuntime);
    expect(previewShell.bootstrap.createPreviewBuildStatusUpdater).toBe(createPreviewBuildStatusUpdater);
    expect(previewShell.bootstrap.createPreviewEditorInteractionFacadeFromEditorHost)
      .toBe(createPreviewEditorInteractionFacadeFromEditorHost);
    expect(previewShell.bootstrap.createPreviewEditorInteractionFacadeFromBrowserHost)
      .toBe(createPreviewEditorInteractionFacadeFromBrowserHost);
    expect(previewShell.bootstrap.createPreviewEditorInteractionFacadeFromRuntime)
      .toBe(createPreviewEditorInteractionFacadeFromRuntime);
    expect(previewShell.bootstrap.createPreviewGridEditorBrowserStateFromBrowserHost)
      .toBe(createPreviewGridEditorBrowserStateFromBrowserHost);
    expect(previewShell.bootstrap.createPreviewGridEditorInstallUnitFromEditorHost)
      .toBe(createPreviewGridEditorInstallUnitFromEditorHost);
    expect(previewShell.bootstrap.createPreviewGridEditorInstallUnitFromBrowserHost)
      .toBe(createPreviewGridEditorInstallUnitFromBrowserHost);
    expect(previewShell.bootstrap.createPreviewGridEditorInstallOptionsFromLegacyEditorHost)
      .toBe(createPreviewGridEditorInstallOptionsFromLegacyEditorHost);
    expect(previewShell.bootstrap.createPreviewGridEditorInstallUnitFromLegacyEditorHost)
      .toBe(createPreviewGridEditorInstallUnitFromLegacyEditorHost);
    expect(previewShell.bootstrap.createPreviewGridEditorRuntimeFromBrowserHost)
      .toBe(createPreviewGridEditorRuntimeFromBrowserHost);
    expect(previewShell.bootstrap.createPreviewEditorSceneFacadeFromRuntime)
      .toBe(createPreviewEditorSceneFacadeFromRuntime);
    expect(previewShell.scene.createPreviewEditorSceneFacadeFromRuntime)
      .toBe(createPreviewEditorSceneFacadeFromRuntime);
    expect(previewShell.bootstrap.createPreviewEditorRuntimeSetFromHost)
      .toBe(createPreviewEditorRuntimeSetFromHost);
    expect(previewShell.bootstrap.createPreviewEditorRuntimeSetFromRuntime)
      .toBe(createPreviewEditorRuntimeSetFromRuntime);
    expect(previewShell.bootstrap.createPreviewEditorRuntimeSet).toBe(createPreviewEditorRuntimeSet);
    expect(previewShell.bootstrap.createBootstrapPreviewEditorRuntimeOptionsFromHost)
      .toBe(createBootstrapPreviewEditorRuntimeOptionsFromHost);
    expect(previewShell.bootstrap.createPreviewOverrideToolbarHostOptions)
      .toBe(createPreviewOverrideToolbarHostOptions);
    expect(previewShell.bootstrap.createPreviewSaveClientRuntime)
      .toBe(createPreviewSaveClientRuntime);
    expect(previewShell.bootstrap.collectPreviewEngineSavePayload).toBeTypeOf('function');
    expect(previewShell.bootstrap.ensurePreviewEngineShellCompatController)
      .toBe(ensurePreviewEngineShellCompatController);
    expect(previewShell.bootstrap.ensurePreviewEngineShellController).toBeTypeOf('function');
    expect(previewShell.bootstrap.ensurePreviewElkPreviewController).toBeTypeOf('function');
    expect(previewShell.bootstrap.getPreviewEngineShellController).toBeTypeOf('function');
    expect(previewShell.bootstrap.initPreviewEngineShellPanel).toBeTypeOf('function');
    expect(previewShell.bootstrap.initPreviewEditorRuntimeHost).toBe(initPreviewEditorRuntimeHost);
    expect(previewShell.bootstrap.isPreviewEngineShellLayoutActive).toBeTypeOf('function');
    expect(previewShell.bootstrap.bootstrapPreviewEditorRuntime).toBe(bootstrapPreviewEditorRuntime);
    expect(previewShell.bootstrap.bootstrapPreviewEditorHost).toBe(bootstrapPreviewEditorHost);
    expect(previewShell.bootstrap.installPreviewEditorTestFacadeHost).toBe(installPreviewEditorTestFacadeHost);
    expect(previewShell.bootstrap.loadPreviewComponentTree).toBe(loadPreviewComponentTree);
    expect(previewShell.bootstrap.loadPreviewGridInfo).toBe(loadPreviewGridInfo);
    expect(previewShell.bootstrap.registerPreviewEditorDocumentBindingsHost).toBe(registerPreviewEditorDocumentBindingsHost);
    expect(previewShell.bootstrap.restorePreviewSelectionIds).toBe(restorePreviewSelectionIds);
    expect(previewShell.bootstrap.syncPreviewArrowModelFromFrameTree).toBe(syncPreviewArrowModelFromFrameTree);
  });

  it('exposes preview-bridge relayout/render aliases under a namespaced contract', () => {
    expect(previewBridge.host.applyFrameTreeRemovalsToPreviewTreeJson).toBeTypeOf('function');
    expect(previewBridge.host.applyPreviewSessionRemovalsToDiagramJson).toBeTypeOf('function');
    expect(previewBridge.host.createPreviewElkViewModeRuntimeFromBrowserHost)
      .toBe(createPreviewElkViewModeRuntimeFromBrowserHost);
    expect(previewBridge.host.createPreviewElkViewModeRuntime).toBe(createPreviewElkViewModeRuntime);
    expect(previewBridge.host.createPreviewLayoutBridgeInstallRuntimeFromLegacyBrowserHost)
      .toBe(createPreviewLayoutBridgeInstallRuntimeFromLegacyBrowserHost);
    expect(previewBridge.host.createPreviewLayoutBridgeRuntimeFromBrowserHost).toBeTypeOf('function');
    expect(previewBridge.host.createPreviewLayoutBridgeRuntime).toBeTypeOf('function');
    expect(previewBridge.host.createPreviewLayoutBridgeState).toBeTypeOf('function');
    expect(previewBridge.host.normalizePreviewLayoutBridgeLocalRelayoutOverrideMode).toBeTypeOf('function');
    expect(previewBridge.host.resolvePreviewLayoutBridgeLocalRelayoutStatus).toBeTypeOf('function');
    expect(previewBridge.host.updatePreviewComponentModelFromLayout).toBeTypeOf('function');
    expect(previewBridge.relayout.collectPreviewRelayoutFrameOverrides).toBeTypeOf('function');
    expect(previewBridge.relayout.createPreviewEditorRelayoutFacadeFromEditorHost)
      .toBe(createPreviewEditorRelayoutFacadeFromEditorHost);
    expect(previewBridge.relayout.createPreviewEditorRelayoutFacadeFromRuntime)
      .toBe(createPreviewEditorRelayoutFacadeFromRuntime);
    expect(previewBridge.relayout.createPreviewRelayoutRuntime).toBe(createPreviewRelayoutRuntime);
    expect(previewBridge.relayout.createPreviewRelayoutRuntimeFromRuntime)
      .toBe(createPreviewRelayoutRuntimeFromRuntime);
    expect(previewBridge.relayout.createPreviewRelayoutRuntimeOptionsFromRuntime)
      .toBe(createPreviewRelayoutRuntimeOptionsFromRuntime);
    expect(previewBridge.relayout.createPreviewRelayoutRuntimeOptionsFromHost)
      .toBe(createPreviewRelayoutRuntimeOptionsFromHost);
    expect(previewBridge.relayout.createPreviewRelayoutRuntimeState).toBe(createPreviewRelayoutRuntimeState);
    expect(previewBridge.relayout.resolvePreviewLayoutRelayoutStatus).toBe(resolvePreviewLayoutRelayoutStatus);
    expect(previewBridge.relayout.resolvePreviewV3RelayoutStatus).toBe(resolvePreviewV3RelayoutStatus);
    expect(previewBridge.relayout.dispatchPreviewClearOverride).toBe(dispatchPreviewClearOverride);
    expect(previewBridge.relayout.dispatchPreviewRelayoutFailureHost).toBe(dispatchPreviewRelayoutFailureHost);
    expect(previewBridge.relayout.dispatchPreviewRelayoutSuccessHost).toBe(dispatchPreviewRelayoutSuccessHost);
    expect(previewBridge.relayout.restorePreviewOverrideEntries).toBeTypeOf('function');
    expect(previewBridge.relayout.runPreviewRelayout).toBeTypeOf('function');
    expect(previewBridge.relayout.createPreviewLiveResizeRelayoutState).toBeTypeOf('function');
    expect(previewBridge.relayout.createPreviewLiveResizeRuntimeFromHost)
      .toBe(createPreviewLiveResizeRuntimeFromHost);
    expect(previewBridge.relayout.createPreviewLiveResizeRuntime).toBe(createPreviewLiveResizeRuntime);
    expect(previewBridge.relayout.schedulePreviewLiveResizeRelayout).toBeTypeOf('function');
    expect(previewBridge.relayout.cancelPreviewLiveResizeRelayout).toBeTypeOf('function');
    expect(previewBridge.relayout.createPreviewStateRestoreRuntimeFromEditorHost)
      .toBe(createPreviewStateRestoreRuntimeFromEditorHost);
    expect(previewBridge.relayout.createPreviewStateRestoreRuntime).toBe(createPreviewStateRestoreRuntime);
    expect(previewBridge.relayout.persistPreviewResizeToFrameOverrides).toBeTypeOf('function');
    expect(previewBridge.render.applyPreviewSvgOverrides).toBe(applyPreviewSvgOverrides);
    expect(previewBridge.render.applyPreviewSvgOverridesHost).toBe(applyPreviewSvgOverridesHost);
    expect(previewBridge.render.collectPreviewFramesById).toBe(collectPreviewFramesById);
    expect(previewBridge.render.collectPreviewPlacedBounds).toBe(collectPreviewPlacedBounds);
    expect(previewBridge.render.fitPreviewSvgToRenderedContent).toBe(fitPreviewSvgToRenderedContent);
    expect(previewBridge.render.patchPreviewFrameGroup).toBe(patchPreviewFrameGroup);
    expect(previewBridge.render.patchPreviewSvgFromLayout).toBe(patchPreviewSvgFromLayout);
    expect(previewBridge.render.previewArrowComponentId).toBeTypeOf('function');
    expect(previewBridge.render.routePreviewArrows).toBeTypeOf('function');
    expect(previewBridge.render.syncPreviewArrowsInModel).toBeTypeOf('function');
    expect(previewBridge.render.createPreviewArrowSvgFragment).toBeTypeOf('function');
    expect(previewBridge.render.patchPreviewArrowSvg).toBeTypeOf('function');
    expect(previewBridge.render.renderFreshPreviewSvg).toBe(renderFreshPreviewSvg);
    expect(previewBridge.render.renderPreviewFrameTreeToSvg).toBe(renderPreviewFrameTreeToSvg);
    expect(previewBridge.render.readPreviewArrowEndpoints).toBeTypeOf('function');
    expect(previewBridge.render.updatePreviewArrowSvg).toBeTypeOf('function');
  });

  it('exposes preview-engine registry and elk aliases under a namespaced contract', () => {
    expect(previewEngines.registry.getPreviewEngine).toBe(getPreviewEngine);
    expect(previewEngines.registry.listPreviewEngines).toBe(listPreviewEngines);
    expect(previewEngines.registry.resolvePreviewEngine).toBe(resolvePreviewEngine);
    expect(previewEngines.registry.serializePreviewEngineManifest).toBe(serializePreviewEngineManifest);
    expect(previewEngines.graph.createPreviewEngineLayoutControlsRuntime)
      .toBe(createPreviewEngineLayoutControlsRuntime);
    expect(previewEngines.graph.createPreviewEngineShellControllerRuntime)
      .toBe(createPreviewEngineShellControllerRuntime);
    expect(previewEngines.elk.createPreviewElkLayoutControlsRuntime)
      .toBe(createPreviewElkLayoutControlsRuntime);
    expect(previewEngines.elk.createPreviewElkShellControllerRuntime)
      .toBe(createPreviewElkShellControllerRuntime);
    expect(previewEngines.elk.ELK_LAYERED_PREVIEW_ENGINE).toBe(ELK_LAYERED_PREVIEW_ENGINE);
    expect(previewEngines.elk.ELK_LAYERED_PARAM_SPECS).toBe(ELK_LAYERED_PARAM_SPECS);
    expect(previewEngines.elk.elkParamGroups).toBe(elkParamGroups);
    expect(previewEngines.elk.ensurePreviewEngineShellController).toBeTypeOf('function');
    expect(previewEngines.elk.renderPreviewElkDebugOverlay).toBe(renderPreviewElkDebugOverlay);
    expect(previewEngines.elk.renderPreviewElkRawView).toBe(renderPreviewElkRawView);
    expect(previewEngines.force.FORCE_PREVIEW_PARAM_SPECS).toBe(FORCE_PREVIEW_PARAM_SPECS);
    expect(previewEngines.force.applyForceNodePatch).toBe(applyForceNodePatch);
  });

  it('exposes a core namespace for layout-bridge-owned runtime helpers', () => {
    expect(Object.keys(core).sort()).toEqual([...CORE_EXPORT_KEYS].sort());
    expect(core.BODY_LINE_STEP).toBe(BODY_LINE_STEP);
    expect(core.BODY_SIZE).toBe(BODY_SIZE);
    expect(core.GRID_GUTTER).toBe(GRID_GUTTER);
    expect(core.ICON_SIZE).toBe(ICON_SIZE);
    expect(core.INSET).toBe(INSET);
    expect(core.annotationTextToSpec).toBe(annotationTextToSpec);
    expect(core.createLine).toBe(createLine);
    expect(core.deserializeFrameDiagramWire).toBe(deserializeFrameDiagramWire);
    expect(core.deserializeFrameWire).toBe(deserializeFrameWire);
    expect(core.effectiveResolvedStrokeWidth).toBe(effectiveResolvedStrokeWidth);
    expect(core.frameOwnedTextBlockGap).toBe(frameOwnedTextBlockGap);
    expect(core.frameOwnedTextBlockRole).toBe(frameOwnedTextBlockRole);
    expect(core.frameOwnedTextBlocks).toBe(frameOwnedTextBlocks);
    expect(core.layoutElkFrameDiagram).toBe(layoutElkFrameDiagram);
    expect(core.layoutFrameTree).toBe(layoutFrameTree);
    expect(core.layoutSequenceDiagram).toBe(layoutSequenceDiagram);
    expect(core.renderSequenceDiagramToSvg).toBe(renderSequenceDiagramToSvg);
    expect(core.resolveStyles).toBe(resolveStyles);
    expect(core.routeArrows).toBe(routeArrows);
    expect(core.sizeToPx).toBe(sizeToPx);
    expect(core.wrapTextLines).toBe(wrapTextLines);
  });

  it('keeps migrated preview-shell bootstrap, inspector, and interaction aliases in parity with root exports', () => {
    expect(previewShell.bootstrap.initPreviewOverrideToolbar).toBe(initPreviewOverrideToolbar);
    expect(previewShell.inspector.resolvePreviewEditableComponentId).toBe(resolvePreviewEditableComponentId);
    expect(previewShell.inspector.applySingleFramePropMutation).toBe(applySingleFramePropMutation);
    expect(previewShell.inspector.applyVisiblePreviewStyleOverride).toBe(applyVisiblePreviewStyleOverride);
    expect(previewShell.inspector.createPreviewInspectorDisplayRuntime).toBe(createPreviewInspectorDisplayRuntime);
    expect(previewShell.inspector.createPreviewInspectorMutationRuntime).toBe(createPreviewInspectorMutationRuntime);
    expect(previewShell.inspector.createPreviewInspectorSelectionRuntime).toBe(createPreviewInspectorSelectionRuntime);
    expect(previewShell.inspector.bindPreviewEditorInspectorActionsFromBrowserHost)
      .toBe(bindPreviewEditorInspectorActionsFromBrowserHost);
    expect(previewShell.inspector.normalizePreviewStyleName).toBe(normalizePreviewStyleName);
    expect(previewShell.inspector.formatPreviewDefinedStyleLabel).toBe(formatPreviewDefinedStyleLabel);
    expect(previewShell.inspector.dispatchPreviewAlignSelectionHost).toBe(dispatchPreviewAlignSelectionHost);
    expect(previewShell.inspector.dispatchPreviewApplySelectionTargetsHost).toBe(dispatchPreviewApplySelectionTargetsHost);
    expect(previewShell.inspector.dispatchPreviewDistributeSelectionHost).toBe(dispatchPreviewDistributeSelectionHost);
    expect(previewShell.inspector.dispatchPreviewMultiFrameAlignHost).toBe(dispatchPreviewMultiFrameAlignHost);
    expect(previewShell.inspector.dispatchPreviewMultiFramePropHost).toBe(dispatchPreviewMultiFramePropHost);
    expect(previewShell.inspector.dispatchPreviewMultiFrameSizeHost).toBe(dispatchPreviewMultiFrameSizeHost);
    expect(previewShell.inspector.dispatchPreviewMultiStyleOverrideHost).toBe(dispatchPreviewMultiStyleOverrideHost);
    expect(previewShell.inspector.dispatchPreviewSingleFrameAlignHost).toBe(dispatchPreviewSingleFrameAlignHost);
    expect(previewShell.inspector.dispatchPreviewSingleFramePropHost).toBe(dispatchPreviewSingleFramePropHost);
    expect(previewShell.inspector.dispatchPreviewSingleFrameSizeHost).toBe(dispatchPreviewSingleFrameSizeHost);
    expect(previewShell.inspector.renderPreviewEmptyInspectorHost).toBe(renderPreviewEmptyInspectorHost);
    expect(previewShell.inspector.renderPreviewBoxStyleOptions).toBe(renderPreviewBoxStyleOptions);
    expect(previewShell.inspector.renderPreviewMultiSelectionInspectorHost).toBe(renderPreviewMultiSelectionInspectorHost);
    expect(previewShell.inspector.renderPreviewMultiSelectionInspectorRuntimeHost).toBe(renderPreviewMultiSelectionInspectorRuntimeHost);
    expect(previewShell.inspector.renderPreviewSelectionInspectorHost).toBe(renderPreviewSelectionInspectorHost);
    expect(previewShell.inspector.renderPreviewSingleSelectionInspectorRuntimeHost).toBe(renderPreviewSingleSelectionInspectorRuntimeHost);
    expect(previewShell.inspector.renderPreviewSingleSelectionInspectorHost).toBe(renderPreviewSingleSelectionInspectorHost);
    expect(previewShell.inspector.resolvePreviewFrameSizePx).toBe(resolvePreviewFrameSizePx);
    expect(previewShell.inspector.resolvePreviewTextEditStartState).toBe(resolvePreviewTextEditStartState);
    expect(previewShell.inspector.schedulePreviewTextEditCommitHost).toBe(schedulePreviewTextEditCommitHost);
    expect(previewShell.inspector.startPreviewTextEditHost).toBe(startPreviewTextEditHost);
    expect(previewShell.inspector.suspendPreviewTextEditSelectionChromeHost).toBe(
      suspendPreviewTextEditSelectionChromeHost,
    );
    expect(previewShell.interaction.applyPreviewSelectionStateSnapshot).toBe(applyPreviewSelectionStateSnapshot);
    expect(previewShell.interaction.clearPreviewSelectionState).toBe(clearPreviewSelectionState);
    expect(previewShell.interaction.applySelectionStateMutation).toBe(applySelectionStateMutation);
    expect(previewShell.interaction.createPreviewArrowWaypointRuntime).toBe(createPreviewArrowWaypointRuntime);
    expect(previewShell.interaction.createPreviewPointerInteractionRuntimeFromHost)
      .toBe(createPreviewPointerInteractionRuntimeFromHost);
    expect(previewShell.interaction.createPreviewPointerInteractionRuntime)
      .toBe(createPreviewPointerInteractionRuntime);
    expect(previewShell.interaction.createPreviewResizeInteractionRuntime)
      .toBe(createPreviewResizeInteractionRuntime);
    expect(previewShell.interaction.createPreviewResizeInteractionRuntimeFromHost)
      .toBe(createPreviewResizeInteractionRuntimeFromHost);
    expect(previewShell.interaction.createPreviewSelectionChromeRuntimeFromHost)
      .toBe(createPreviewSelectionChromeRuntimeFromHost);
    expect(previewShell.interaction.createPreviewSelectionChromeRuntime)
      .toBe(createPreviewSelectionChromeRuntime);
    expect(previewShell.interaction.createPreviewSelectionRuntime).toBe(createPreviewSelectionRuntime);
    expect(previewShell.interaction.createPreviewStageBindingRuntimeFromHost)
      .toBe(createPreviewStageBindingRuntimeFromHost);
    expect(previewShell.interaction.createPreviewStageBindingRuntime)
      .toBe(createPreviewStageBindingRuntime);
    expect(previewShell.interaction.bindPreviewStageSvgInteraction).toBe(bindPreviewStageSvgInteraction);
    expect(previewShell.interaction.bindPreviewStageSvgInteractionHost).toBe(bindPreviewStageSvgInteractionHost);
    expect(previewShell.interaction.collectPreviewRecursiveRelayoutEntries).toBe(collectPreviewRecursiveRelayoutEntries);
    expect(previewShell.interaction.collectPreviewSelectionActionInfo).toBe(collectPreviewSelectionActionInfo);
    expect(previewShell.interaction.createPreviewDragStartState).toBe(createPreviewDragStartState);
    expect(previewShell.interaction.createPreviewResizeStartState).toBe(createPreviewResizeStartState);
    expect(previewShell.interaction.deletePreviewSelectedFramesHost).toBe(deletePreviewSelectedFramesHost);
    expect(previewShell.interaction.dispatchPreviewDragMove).toBe(dispatchPreviewDragMove);
    expect(previewShell.interaction.dispatchPreviewDeleteFramesHost).toBe(dispatchPreviewDeleteFramesHost);
    expect(previewShell.interaction.dispatchPreviewDragMoveHost).toBe(dispatchPreviewDragMoveHost);
    expect(previewShell.interaction.dispatchPreviewKeyboardShortcut).toBe(dispatchPreviewKeyboardShortcut);
    expect(previewShell.interaction.createPreviewKeyboardRuntime).toBe(createPreviewKeyboardRuntime);
    expect(previewShell.interaction.createPreviewKeyboardRuntimeFromHost)
      .toBe(createPreviewKeyboardRuntimeFromHost);
    expect(previewShell.interaction.dispatchPreviewResizeMove).toBe(dispatchPreviewResizeMove);
    expect(previewShell.interaction.dispatchPreviewResizeMoveHost).toBe(dispatchPreviewResizeMoveHost);
    expect(previewShell.interaction.dispatchPreviewWaypointDragMoveHost).toBe(dispatchPreviewWaypointDragMoveHost);
    expect(previewShell.interaction.findPreviewArrowAtPoint).toBe(findPreviewArrowAtPoint);
    expect(previewShell.interaction.findDeepestPreviewComponent).toBe(findDeepestPreviewComponent);
    expect(previewShell.interaction.findPreviewComponentAtDepth).toBe(findPreviewComponentAtDepth);
    expect(previewShell.interaction.handlePreviewDoubleClickSelectionHost).toBe(handlePreviewDoubleClickSelectionHost);
    expect(previewShell.interaction.readPreviewArrowPointsHost).toBe(readPreviewArrowPointsHost);
    expect(previewShell.interaction.removePreviewHandlesHost).toBe(removePreviewHandlesHost);
    expect(previewShell.interaction.resolvePrimarySelectedId).toBe(resolvePrimarySelectedId);
    expect(previewShell.interaction.resolvePreviewComponentSelectionState).toBe(resolvePreviewComponentSelectionState);
    expect(previewShell.interaction.resolvePreviewDiagramRootFrameId).toBe(resolvePreviewDiagramRootFrameId);
    expect(previewShell.interaction.resolvePreviewResizeHandlePlan).toBe(resolvePreviewResizeHandlePlan);
    expect(previewShell.interaction.rebuildPreviewArrowSvgHost).toBe(rebuildPreviewArrowSvgHost);
    expect(previewShell.interaction.renderPreviewWaypointHandlesHost).toBe(renderPreviewWaypointHandlesHost);
    expect(previewShell.interaction.renderPreviewTreeSelectionHost).toBe(renderPreviewTreeSelectionHost);
    expect(previewShell.interaction.restorePreviewPropagatedResizeOverrides).toBe(restorePreviewPropagatedResizeOverrides);
    expect(previewShell.interaction.showPreviewResizeHandlesHost).toBe(showPreviewResizeHandlesHost);
    expect(previewShell.interaction.startPreviewPointerInteractionHost).toBe(startPreviewPointerInteractionHost);
    expect(previewShell.interaction.startPreviewResizeHost).toBe(startPreviewResizeHost);
    expect(previewShell.interaction.startPreviewWaypointDragHost).toBe(startPreviewWaypointDragHost);
    expect(previewShell.interaction.syncPreviewSelectionUi).toBe(syncPreviewSelectionUi);
    expect(previewShell.interaction.updatePreviewArrowVisualHost).toBe(updatePreviewArrowVisualHost);
    expect(previewShell.scene.applyPreviewWaypointOverridesHost).toBe(applyPreviewWaypointOverridesHost);
    expect(previewShell.scene.createPreviewEditorSceneFacadeFromEditorHost)
      .toBe(createPreviewEditorSceneFacadeFromEditorHost);
    expect(previewShell.scene.createPreviewGridRuntimeFromEditorHost)
      .toBe(createPreviewGridRuntimeFromEditorHost);
    expect(previewShell.scene.createPreviewGridRuntimeHost).toBe(createPreviewGridRuntimeHost);
    expect(previewShell.scene.cyclePreviewGuideModeHost).toBe(cyclePreviewGuideModeHost);
    expect(previewShell.scene.dispatchPreviewGridControlChangeHost).toBe(dispatchPreviewGridControlChangeHost);
    expect(previewShell.scene.populatePreviewGridControls).toBe(populatePreviewGridControls);
    expect(previewShell.scene.populatePreviewGridControlsHost).toBe(populatePreviewGridControlsHost);
    expect(previewShell.scene.readPreviewGridControlStateFromDom).toBe(readPreviewGridControlStateFromDom);
    expect(previewShell.scene.refreshPreviewGridInfoFromLayoutHost).toBe(refreshPreviewGridInfoFromLayoutHost);
    expect(previewShell.scene.refreshPreviewSceneHost).toBe(refreshPreviewSceneHost);
    expect(previewShell.scene.rerenderPreviewStageFromModelHost).toBe(rerenderPreviewStageFromModelHost);
    expect(previewShell.scene.rerenderPreviewStageHost).toBe(rerenderPreviewStageHost);
    expect(previewShell.scene.renderPreviewGridOverlayHost).toBe(renderPreviewGridOverlayHost);
    expect(previewShell.scene.resolvePreviewGridControlRuntimeUpdate).toBe(resolvePreviewGridControlRuntimeUpdate);
    expect(previewShell.scene.resolvePreviewGridControlRuntimeUpdateHost).toBe(resolvePreviewGridControlRuntimeUpdateHost);
    expect(previewShell.scene.updatePreviewOverrideSummaryHost).toBe(updatePreviewOverrideSummaryHost);
  });
});
